export const content = String.raw`## Principle

A cyclic group is a group whose elements are all produced by repeatedly applying the group operation to one element. That element is called a generator.

Cyclic groups model repeated processes, such as applying the same rotation again and again until a physical configuration returns to its start.

## Notation

- \\(g\\) is a generator candidate.
- \\(g^n\\) is the result of applying the group operation repeatedly using \\(g\\).
- \\(g^0=e\\), where \\(e\\) is the identity element.
- \\(\langle g\rangle\\) is the set generated by \\(g\\).
- The order of an element is the smallest positive integer \\(n\\) such that \\(g^n=e\\), if such an integer exists.
- \\(r\\) is a rotation used as a generator in examples.

<Equation label="Generated group" tex="\langle g\rangle=\{g^n:n\in\mathbb Z\}" />

## Method

To test whether a finite group is cyclic:

1. Choose an element \\(g\\) as a generator candidate.
2. List the powers \\(g^0,g^1,g^2,\\ldots\\).
3. Stop when the identity \\(e\\) first repeats.
4. Compare the listed elements with the whole group.
5. If every group element appears, then \\(g\\) generates the group.

## Rules

- In multiplicative notation, \\(g^m g^n=g^{m+n}\\).
- A finite cyclic group repeats after the generator reaches the identity again.
- The repeated identity at the end of the cycle is not counted as a new element.
- Every cyclic group is abelian, so its elements commute.

## Examples

Let \\(r\\) be a \\(120^\circ\\) rotation of an equilateral triangle. Repeated rotations by \\(120^\circ\\) produce all rotational symmetries of the triangle.

<Equation label="Triangle rotation powers" tex="r^0=e,\quad r^1=r,\quad r^2=r^2,\quad r^3=e" />

The first return to the identity occurs at \\(r^3=e\\). The distinct elements before that repeat are \\(e\\), \\(r\\), and \\(r^2\\).

Therefore the rotational symmetry group of the equilateral triangle is cyclic of order \\(3\\), generated by \\(r\\).

## Checks

- Stop at the first return to the identity.
- Do not count the repeated identity twice.
- Check that the powers of the generator produce every element, not just several elements.
- Distinguish the order of one element from the number of elements in a larger group.`;
