/* This file is generated by apps/academy/scripts/generate-question-registry.mjs. */
/* Do not edit manually. */

import alternatingCurrentLrcSeriesCircuitsInAcQuestionData from "./questions/alternating-current/lrc-series-circuits-in-ac.json";
import alternatingCurrentPhasorsAndAcSignalsQuestionData from "./questions/alternating-current/phasors-and-ac-signals.json";
import alternatingCurrentPowerInAcCircuitsQuestionData from "./questions/alternating-current/power-in-ac-circuits.json";
import alternatingCurrentResistanceAndReactanceQuestionData from "./questions/alternating-current/resistance-and-reactance.json";
import alternatingCurrentResonanceInAcCircuitsQuestionData from "./questions/alternating-current/resonance-in-ac-circuits.json";
import alternatingCurrentTransformersQuestionData from "./questions/alternating-current/transformers.json";
import applyingForceModelsDynamicsOfCircularMotionQuestionData from "./questions/applying-force-models/dynamics-of-circular-motion.json";
import applyingForceModelsEquilibriumWithNewtonsFirstLawQuestionData from "./questions/applying-force-models/equilibrium-with-newtons-first-law.json";
import applyingForceModelsFourFundamentalInteractionsQuestionData from "./questions/applying-force-models/four-fundamental-interactions.json";
import applyingForceModelsParticleDynamicsWithNewtonsSecondLawQuestionData from "./questions/applying-force-models/particle-dynamics-with-newtons-second-law.json";
import applyingForceModelsStaticAndKineticFrictionQuestionData from "./questions/applying-force-models/static-and-kinetic-friction.json";
import atomicQuantumStructureElectronSpinQuestionData from "./questions/atomic-quantum-structure/electron-spin.json";
import atomicQuantumStructureExclusionPrincipleQuestionData from "./questions/atomic-quantum-structure/exclusion-principle.json";
import atomicQuantumStructureHydrogenAtomQuestionData from "./questions/atomic-quantum-structure/hydrogen-atom.json";
import atomicQuantumStructureManyElectronAtomsQuestionData from "./questions/atomic-quantum-structure/many-electron-atoms.json";
import atomicQuantumStructureParticleInAThreeDimensionalBoxQuestionData from "./questions/atomic-quantum-structure/particle-in-a-three-dimensional-box.json";
import atomicQuantumStructureQuantumEntanglementQuestionData from "./questions/atomic-quantum-structure/quantum-entanglement.json";
import atomicQuantumStructureThreeDimensionalSchrodingerEquationQuestionData from "./questions/atomic-quantum-structure/three-dimensional-schrodinger-equation.json";
import atomicQuantumStructureXRaySpectraQuestionData from "./questions/atomic-quantum-structure/x-ray-spectra.json";
import atomicQuantumStructureZeemanEffectQuestionData from "./questions/atomic-quantum-structure/zeeman-effect.json";
import capacitorsDielectricsCapacitanceQuestionData from "./questions/capacitors-dielectrics/capacitance.json";
import capacitorsDielectricsDielectricsQuestionData from "./questions/capacitors-dielectrics/dielectrics.json";
import capacitorsDielectricsGaussSLawInMaterialsQuestionData from "./questions/capacitors-dielectrics/gauss-s-law-in-materials.json";
import capacitorsDielectricsMolecularViewOfInducedChargeQuestionData from "./questions/capacitors-dielectrics/molecular-view-of-induced-charge.json";
import capacitorsDielectricsSeriesAndParallelCapacitorsQuestionData from "./questions/capacitors-dielectrics/series-and-parallel-capacitors.json";
import capacitorsDielectricsStoredEnergyAndFieldEnergyQuestionData from "./questions/capacitors-dielectrics/stored-energy-and-field-energy.json";
import currentResistanceElectricCurrentQuestionData from "./questions/current-resistance/electric-current.json";
import currentResistanceElectricPowerQuestionData from "./questions/current-resistance/electric-power.json";
import currentResistanceEmfAndCircuitModelsQuestionData from "./questions/current-resistance/emf-and-circuit-models.json";
import currentResistanceMicroscopicModelOfConductionQuestionData from "./questions/current-resistance/microscopic-model-of-conduction.json";
import currentResistanceResistanceQuestionData from "./questions/current-resistance/resistance.json";
import currentResistanceResistivityQuestionData from "./questions/current-resistance/resistivity.json";
import dcCircuitsElectricalMetersQuestionData from "./questions/dc-circuits/electrical-meters.json";
import dcCircuitsKirchhoffAnalysisQuestionData from "./questions/dc-circuits/kirchhoff-analysis.json";
import dcCircuitsPowerDistributionQuestionData from "./questions/dc-circuits/power-distribution.json";
import dcCircuitsRcTransientsQuestionData from "./questions/dc-circuits/rc-transients.json";
import dcCircuitsSeriesAndParallelResistorNetworksQuestionData from "./questions/dc-circuits/series-and-parallel-resistor-networks.json";
import diffractionCircularAperturesAndResolutionQuestionData from "./questions/diffraction/circular-apertures-and-resolution.json";
import diffractionDiffractionGratingsQuestionData from "./questions/diffraction/diffraction-gratings.json";
import diffractionFresnelAndFraunhoferRegimesQuestionData from "./questions/diffraction/fresnel-and-fraunhofer-regimes.json";
import diffractionHolographyQuestionData from "./questions/diffraction/holography.json";
import diffractionIntensityInSingleSlitPatternsQuestionData from "./questions/diffraction/intensity-in-single-slit-patterns.json";
import diffractionMultipleSlitPatternsQuestionData from "./questions/diffraction/multiple-slit-patterns.json";
import diffractionSingleSlitDiffractionQuestionData from "./questions/diffraction/single-slit-diffraction.json";
import diffractionXRayDiffractionQuestionData from "./questions/diffraction/x-ray-diffraction.json";
import electricChargeFieldsCalculatingElectricFieldsQuestionData from "./questions/electric-charge-fields/calculating-electric-fields.json";
import electricChargeFieldsChargeInductionQuestionData from "./questions/electric-charge-fields/charge-induction.json";
import electricChargeFieldsConductorsAndInsulatorsQuestionData from "./questions/electric-charge-fields/conductors-and-insulators.json";
import electricChargeFieldsCoulombForcesQuestionData from "./questions/electric-charge-fields/coulomb-forces.json";
import electricChargeFieldsElectricChargeQuestionData from "./questions/electric-charge-fields/electric-charge.json";
import electricChargeFieldsElectricDipolesQuestionData from "./questions/electric-charge-fields/electric-dipoles.json";
import electricChargeFieldsElectricFieldsAndForcesQuestionData from "./questions/electric-charge-fields/electric-fields-and-forces.json";
import electricChargeFieldsFieldLineRepresentationsQuestionData from "./questions/electric-charge-fields/field-line-representations.json";
import electricPotentialCalculatingPotentialQuestionData from "./questions/electric-potential/calculating-potential.json";
import electricPotentialElectricPotentialEnergyQuestionData from "./questions/electric-potential/electric-potential-energy.json";
import electricPotentialElectricPotentialQuestionData from "./questions/electric-potential/electric-potential.json";
import electricPotentialEquipotentialSurfacesQuestionData from "./questions/electric-potential/equipotential-surfaces.json";
import electricPotentialPotentialGradientsQuestionData from "./questions/electric-potential/potential-gradients.json";
import electromagneticInductionDisplacementCurrentQuestionData from "./questions/electromagnetic-induction/displacement-current.json";
import electromagneticInductionEddyCurrentsQuestionData from "./questions/electromagnetic-induction/eddy-currents.json";
import electromagneticInductionFaradaySLawQuestionData from "./questions/electromagnetic-induction/faraday-s-law.json";
import electromagneticInductionInducedElectricFieldsQuestionData from "./questions/electromagnetic-induction/induced-electric-fields.json";
import electromagneticInductionInductionObservationsQuestionData from "./questions/electromagnetic-induction/induction-observations.json";
import electromagneticInductionLenzSLawQuestionData from "./questions/electromagnetic-induction/lenz-s-law.json";
import electromagneticInductionMaxwellSEquationsQuestionData from "./questions/electromagnetic-induction/maxwell-s-equations.json";
import electromagneticInductionMotionalEmfQuestionData from "./questions/electromagnetic-induction/motional-emf.json";
import electromagneticInductionSuperconductivityQuestionData from "./questions/electromagnetic-induction/superconductivity.json";
import electromagneticWavesEnergyAndMomentumInElectromagneticWavesQuestionData from "./questions/electromagnetic-waves/energy-and-momentum-in-electromagnetic-waves.json";
import electromagneticWavesMaxwellSEquationsToWavesQuestionData from "./questions/electromagnetic-waves/maxwell-s-equations-to-waves.json";
import electromagneticWavesPlaneWavesAndLightSpeedQuestionData from "./questions/electromagnetic-waves/plane-waves-and-light-speed.json";
import electromagneticWavesSinusoidalElectromagneticWavesQuestionData from "./questions/electromagnetic-waves/sinusoidal-electromagnetic-waves.json";
import electromagneticWavesStandingElectromagneticWavesQuestionData from "./questions/electromagnetic-waves/standing-electromagnetic-waves.json";
import entropyHeatEnginesEntropyQuestionData from "./questions/entropy-heat-engines/entropy.json";
import equilibriumMaterialsCenterOfGravityQuestionData from "./questions/equilibrium-materials/center-of-gravity.json";
import equilibriumMaterialsConditionsForStaticEquilibriumQuestionData from "./questions/equilibrium-materials/conditions-for-static-equilibrium.json";
import equilibriumMaterialsElasticModuliQuestionData from "./questions/equilibrium-materials/elastic-moduli.json";
import equilibriumMaterialsElasticVersusPlasticBehaviorQuestionData from "./questions/equilibrium-materials/elastic-versus-plastic-behavior.json";
import equilibriumMaterialsSolvingRigidBodyEquilibriumQuestionData from "./questions/equilibrium-materials/solving-rigid-body-equilibrium.json";
import equilibriumMaterialsStressAndStrainQuestionData from "./questions/equilibrium-materials/stress-and-strain.json";
import firstLawThermodynamicsAdiabaticIdealGasProcessesQuestionData from "./questions/first-law-thermodynamics/adiabatic-ideal-gas-processes.json";
import firstLawThermodynamicsCommonThermodynamicProcessesQuestionData from "./questions/first-law-thermodynamics/common-thermodynamic-processes.json";
import firstLawThermodynamicsHeatCapacityOfIdealGasesQuestionData from "./questions/first-law-thermodynamics/heat-capacity-of-ideal-gases.json";
import firstLawThermodynamicsInternalEnergyAndTheFirstLawQuestionData from "./questions/first-law-thermodynamics/internal-energy-and-the-first-law.json";
import firstLawThermodynamicsInternalEnergyOfIdealGasesQuestionData from "./questions/first-law-thermodynamics/internal-energy-of-ideal-gases.json";
import firstLawThermodynamicsPathsBetweenStatesQuestionData from "./questions/first-law-thermodynamics/paths-between-states.json";
import firstLawThermodynamicsThermodynamicSystemsQuestionData from "./questions/first-law-thermodynamics/thermodynamic-systems.json";
import firstLawThermodynamicsWorkDuringVolumeChangesQuestionData from "./questions/first-law-thermodynamics/work-during-volume-changes.json";
import fluidsBernoulliModelsQuestionData from "./questions/fluids/bernoulli-models.json";
import fluidsBuoyancyQuestionData from "./questions/fluids/buoyancy.json";
import fluidsDensityInGasesAndLiquidsQuestionData from "./questions/fluids/density-in-gases-and-liquids.json";
import fluidsFluidFlowQuestionData from "./questions/fluids/fluid-flow.json";
import fluidsPressureInFluidsQuestionData from "./questions/fluids/pressure-in-fluids.json";
import fluidsViscosityAndTurbulenceQuestionData from "./questions/fluids/viscosity-and-turbulence.json";
import forcesNewtonsLawsActionReactionPairsQuestionData from "./questions/forces-newtons-laws/action-reaction-pairs.json";
import forcesNewtonsLawsDrawingForceDiagramsQuestionData from "./questions/forces-newtons-laws/drawing-free-body-diagrams.json";
import forcesNewtonsLawsEquilibriumAndInertiaQuestionData from "./questions/forces-newtons-laws/equilibrium-and-inertia.json";
import forcesNewtonsLawsForceMassAndAccelerationQuestionData from "./questions/forces-newtons-laws/force-mass-and-acceleration.json";
import forcesNewtonsLawsForcesAsInteractionsQuestionData from "./questions/forces-newtons-laws/forces-as-interactions.json";
import forcesNewtonsLawsWeightVersusMassQuestionData from "./questions/forces-newtons-laws/weight-versus-mass.json";
import gausssLawChargeAndElectricFluxQuestionData from "./questions/gausss-law/charge-and-electric-flux.json";
import gausssLawChargeOnConductorsQuestionData from "./questions/gausss-law/charge-on-conductors.json";
import gausssLawComputingElectricFluxQuestionData from "./questions/gausss-law/computing-electric-flux.json";
import gausssLawGaussSLawQuestionData from "./questions/gausss-law/gauss-s-law.json";
import gausssLawSymmetryApplicationsOfGaussSLawQuestionData from "./questions/gausss-law/symmetry-applications-of-gauss-s-law.json";
import geometricOpticsCamerasQuestionData from "./questions/geometric-optics/cameras.json";
import geometricOpticsMagnifiersQuestionData from "./questions/geometric-optics/magnifiers.json";
import geometricOpticsMicroscopesQuestionData from "./questions/geometric-optics/microscopes.json";
import geometricOpticsPlaneSurfaceReflectionQuestionData from "./questions/geometric-optics/plane-surface-reflection.json";
import geometricOpticsPlaneSurfaceRefractionQuestionData from "./questions/geometric-optics/plane-surface-refraction.json";
import geometricOpticsSphericalMirrorsQuestionData from "./questions/geometric-optics/spherical-mirrors.json";
import geometricOpticsSphericalRefractionQuestionData from "./questions/geometric-optics/spherical-refraction.json";
import geometricOpticsTelescopesQuestionData from "./questions/geometric-optics/telescopes.json";
import geometricOpticsTheEyeQuestionData from "./questions/geometric-optics/the-eye.json";
import geometricOpticsThinLensesQuestionData from "./questions/geometric-optics/thin-lenses.json";
import gravitationApparentWeightOnEarthQuestionData from "./questions/gravitation/apparent-weight-on-earth.json";
import gravitationBlackHolesQuestionData from "./questions/gravitation/black-holes.json";
import gravitationFieldsFromSphericalMassesQuestionData from "./questions/gravitation/fields-from-spherical-masses.json";
import gravitationKeplerModelsOfOrbitsQuestionData from "./questions/gravitation/kepler-models-of-orbits.json";
import gravitationSatelliteMotionQuestionData from "./questions/gravitation/satellite-motion.json";
import gravitationUniversalGravitationQuestionData from "./questions/gravitation/universal-gravitation.json";
import gravitationWeightInGravitationalFieldsQuestionData from "./questions/gravitation/weight-in-gravitational-fields.json";
import inductanceLcOscillationsQuestionData from "./questions/inductance/lc-oscillations.json";
import inductanceLrcSeriesCircuitsQuestionData from "./questions/inductance/lrc-series-circuits.json";
import inductanceMagneticFieldEnergyQuestionData from "./questions/inductance/magnetic-field-energy.json";
import inductanceMutualInductanceQuestionData from "./questions/inductance/mutual-inductance.json";
import inductanceRlTransientsQuestionData from "./questions/inductance/rl-transients.json";
import inductanceSelfInductanceAndInductorsQuestionData from "./questions/inductance/self-inductance-and-inductors.json";
import interferenceCoherenceAndInterferenceQuestionData from "./questions/interference/coherence-and-interference.json";
import interferenceIntensityInInterferencePatternsQuestionData from "./questions/interference/intensity-in-interference-patterns.json";
import interferenceMichelsonInterferometerQuestionData from "./questions/interference/michelson-interferometer.json";
import interferenceThinFilmInterferenceQuestionData from "./questions/interference/thin-film-interference.json";
import interferenceTwoSourceLightInterferenceQuestionData from "./questions/interference/two-source-light-interference.json";
import lightPropagationDispersionQuestionData from "./questions/light-propagation/dispersion.json";
import lightPropagationHuygensPrincipleQuestionData from "./questions/light-propagation/huygens-principle.json";
import lightPropagationNatureOfLightQuestionData from "./questions/light-propagation/nature-of-light.json";
import lightPropagationPolarizationQuestionData from "./questions/light-propagation/polarization.json";
import lightPropagationReflectionAndRefractionQuestionData from "./questions/light-propagation/reflection-and-refraction.json";
import lightPropagationScatteringQuestionData from "./questions/light-propagation/scattering.json";
import lightPropagationTotalInternalReflectionQuestionData from "./questions/light-propagation/total-internal-reflection.json";
import magneticFieldSourcesAmpereSLawQuestionData from "./questions/magnetic-field-sources/ampere-s-law.json";
import magneticFieldSourcesBiotSavartForCurrentElementsQuestionData from "./questions/magnetic-field-sources/biot-savart-for-current-elements.json";
import magneticFieldSourcesFieldsAroundStraightCurrentsQuestionData from "./questions/magnetic-field-sources/fields-around-straight-currents.json";
import magneticFieldSourcesFieldsFromCurrentLoopsQuestionData from "./questions/magnetic-field-sources/fields-from-current-loops.json";
import magneticFieldSourcesFieldsFromMovingChargesQuestionData from "./questions/magnetic-field-sources/fields-from-moving-charges.json";
import magneticFieldSourcesForcesBetweenParallelCurrentsQuestionData from "./questions/magnetic-field-sources/forces-between-parallel-currents.json";
import magneticFieldSourcesMagneticMaterialsQuestionData from "./questions/magnetic-field-sources/magnetic-materials.json";
import magneticFieldSourcesSymmetryApplicationsOfAmpereSLawQuestionData from "./questions/magnetic-field-sources/symmetry-applications-of-ampere-s-law.json";
import magneticFieldsForcesChargedParticlesInMagneticFieldsQuestionData from "./questions/magnetic-fields-forces/charged-particles-in-magnetic-fields.json";
import magneticFieldsForcesDcMotorsQuestionData from "./questions/magnetic-fields-forces/dc-motors.json";
import magneticFieldsForcesForcesOnCurrentCarryingConductorsQuestionData from "./questions/magnetic-fields-forces/forces-on-current-carrying-conductors.json";
import magneticFieldsForcesHallEffectQuestionData from "./questions/magnetic-fields-forces/hall-effect.json";
import magneticFieldsForcesMagneticFieldLinesQuestionData from "./questions/magnetic-fields-forces/magnetic-field-lines.json";
import magneticFieldsForcesMagneticFieldsQuestionData from "./questions/magnetic-fields-forces/magnetic-fields.json";
import magneticFieldsForcesMagneticFluxQuestionData from "./questions/magnetic-fields-forces/magnetic-flux.json";
import magneticFieldsForcesMagnetismBasicsQuestionData from "./questions/magnetic-fields-forces/magnetism-basics.json";
import magneticFieldsForcesParticleMotionApplicationsQuestionData from "./questions/magnetic-fields-forces/particle-motion-applications.json";
import magneticFieldsForcesTorqueOnCurrentLoopsQuestionData from "./questions/magnetic-fields-forces/torque-on-current-loops.json";
import matterThermalScaleEquationsOfStateQuestionData from "./questions/matter-thermal-scale/equations-of-state.json";
import matterThermalScaleHeatCapacityQuestionData from "./questions/matter-thermal-scale/heat-capacity.json";
import matterThermalScaleIdealGasModelQuestionData from "./questions/matter-thermal-scale/ideal-gas-model.json";
import matterThermalScaleMolecularPropertiesOfMatterQuestionData from "./questions/matter-thermal-scale/molecular-properties-of-matter.json";
import matterThermalScaleMolecularSpeedsQuestionData from "./questions/matter-thermal-scale/molecular-speeds.json";
import matterThermalScalePhasesOfMatterQuestionData from "./questions/matter-thermal-scale/phases-of-matter.json";
import matterWavesAtomicSpectraQuestionData from "./questions/matter-waves/atomic-spectra.json";
import matterWavesBohrEnergyLevelsQuestionData from "./questions/matter-waves/bohr-energy-levels.json";
import matterWavesContinuousSpectraQuestionData from "./questions/matter-waves/continuous-spectra.json";
import matterWavesElectronWavesQuestionData from "./questions/matter-waves/electron-waves.json";
import matterWavesLasersQuestionData from "./questions/matter-waves/lasers.json";
import matterWavesNuclearAtomQuestionData from "./questions/matter-waves/nuclear-atom.json";
import matterWavesUncertaintyRevisitedQuestionData from "./questions/matter-waves/uncertainty-revisited.json";
import measurementVectorsAReliableProblemSolvingProcessQuestionData from "./questions/measurement-vectors/a-reliable-problem-solving-process.json";
import measurementVectorsAddingVectorsGeometricallyQuestionData from "./questions/measurement-vectors/adding-vectors-geometrically.json";
import measurementVectorsDotAndCrossProductsQuestionData from "./questions/measurement-vectors/dot-and-cross-products.json";
import measurementVectorsEstimationAndScaleSenseQuestionData from "./questions/measurement-vectors/estimation-and-scale-sense.json";
import measurementVectorsHowPhysicsBuildsModelsQuestionData from "./questions/measurement-vectors/how-physics-builds-models.json";
import measurementVectorsMeasurementUncertaintyQuestionData from "./questions/measurement-vectors/measurement-uncertainty.json";
import measurementVectorsResolvingVectorsIntoComponentsQuestionData from "./questions/measurement-vectors/resolving-vectors-into-components.json";
import measurementVectorsSignificantFiguresQuestionData from "./questions/measurement-vectors/significant-figures.json";
import measurementVectorsUnitConversionWithoutGuessworkQuestionData from "./questions/measurement-vectors/unit-conversion-without-guesswork.json";
import measurementVectorsUnitVectorNotationQuestionData from "./questions/measurement-vectors/unit-vector-notation.json";
import measurementVectorsUnitsAndMeasurementStandardsQuestionData from "./questions/measurement-vectors/units-and-measurement-standards.json";
import mechanicalWavesBoundaryConditionsQuestionData from "./questions/mechanical-waves/boundary-conditions.json";
import mechanicalWavesEnergyTransportInWavesQuestionData from "./questions/mechanical-waves/energy-transport-in-waves.json";
import mechanicalWavesMathematicalWaveDescriptionsQuestionData from "./questions/mechanical-waves/mathematical-wave-descriptions.json";
import mechanicalWavesPeriodicWavePatternsQuestionData from "./questions/mechanical-waves/periodic-wave-patterns.json";
import mechanicalWavesSpeedOfTransverseWavesQuestionData from "./questions/mechanical-waves/speed-of-transverse-waves.json";
import mechanicalWavesStandingWavesOnStringsQuestionData from "./questions/mechanical-waves/standing-waves-on-strings.json";
import mechanicalWavesStringNormalModesQuestionData from "./questions/mechanical-waves/string-normal-modes.json";
import mechanicalWavesSuperpositionQuestionData from "./questions/mechanical-waves/superposition.json";
import mechanicalWavesTypesOfMechanicalWavesQuestionData from "./questions/mechanical-waves/types-of-mechanical-waves.json";
import momentumSystemsCenterOfMassQuestionData from "./questions/momentum-systems/center-of-mass.json";
import momentumSystemsCollisionsAsMomentumProblemsQuestionData from "./questions/momentum-systems/collisions-as-momentum-problems.json";
import momentumSystemsElasticCollisionModelsQuestionData from "./questions/momentum-systems/elastic-collision-models.json";
import momentumSystemsMomentumAndImpulseQuestionData from "./questions/momentum-systems/momentum-and-impulse.json";
import momentumSystemsMomentumConservationQuestionData from "./questions/momentum-systems/momentum-conservation.json";
import momentumSystemsRocketMotionQuestionData from "./questions/momentum-systems/rocket-motion.json";
import motionInSpaceAccelerationVectorsQuestionData from "./questions/motion-in-space/acceleration-vectors.json";
import motionInSpaceCircularMotionKinematicsQuestionData from "./questions/motion-in-space/circular-motion-kinematics.json";
import motionInSpacePositionAndVelocityVectorsQuestionData from "./questions/motion-in-space/position-and-velocity-vectors.json";
import motionInSpaceProjectileModelsQuestionData from "./questions/motion-in-space/projectile-models.json";
import motionInSpaceRelativeMotionQuestionData from "./questions/motion-in-space/relative-motion.json";
import nuclearPhysicsActivityAndHalfLifeQuestionData from "./questions/nuclear-physics/activity-and-half-life.json";
import nuclearPhysicsBindingEnergyQuestionData from "./questions/nuclear-physics/binding-energy.json";
import nuclearPhysicsBiologicalEffectsOfRadiationQuestionData from "./questions/nuclear-physics/biological-effects-of-radiation.json";
import nuclearPhysicsFissionQuestionData from "./questions/nuclear-physics/fission.json";
import nuclearPhysicsFusionQuestionData from "./questions/nuclear-physics/fusion.json";
import nuclearPhysicsNuclearPropertiesQuestionData from "./questions/nuclear-physics/nuclear-properties.json";
import nuclearPhysicsNuclearReactionsQuestionData from "./questions/nuclear-physics/nuclear-reactions.json";
import nuclearPhysicsNuclearStabilityQuestionData from "./questions/nuclear-physics/nuclear-stability.json";
import nuclearPhysicsNuclearStructureQuestionData from "./questions/nuclear-physics/nuclear-structure.json";
import nuclearPhysicsRadioactivityQuestionData from "./questions/nuclear-physics/radioactivity.json";
import oneDimensionalMotionAccelerationAsARateOfChangeQuestionData from "./questions/one-dimensional-motion/acceleration-as-a-rate-of-change.json";
import oneDimensionalMotionAverageVelocityQuestionData from "./questions/one-dimensional-motion/average-velocity.json";
import oneDimensionalMotionConstantAccelerationModelsQuestionData from "./questions/one-dimensional-motion/constant-acceleration-models.json";
import oneDimensionalMotionFreeFallMotionQuestionData from "./questions/one-dimensional-motion/free-fall-motion.json";
import oneDimensionalMotionInstantaneousVelocityQuestionData from "./questions/one-dimensional-motion/instantaneous-velocity.json";
import oneDimensionalMotionPositionAndTimeQuestionData from "./questions/one-dimensional-motion/position-and-time.json";
import oneDimensionalMotionPositionAndVelocityFromCalculusQuestionData from "./questions/one-dimensional-motion/position-and-velocity-from-calculus.json";
import oscillationsApplicationsOfHarmonicMotionQuestionData from "./questions/oscillations/applications-of-harmonic-motion.json";
import oscillationsDampingQuestionData from "./questions/oscillations/damping.json";
import oscillationsDescribingOscillationQuestionData from "./questions/oscillations/describing-oscillation.json";
import oscillationsDrivenOscillationsAndResonanceQuestionData from "./questions/oscillations/driven-oscillations-and-resonance.json";
import oscillationsEnergyInOscillatorsQuestionData from "./questions/oscillations/energy-in-oscillators.json";
import oscillationsPhysicalPendulumsQuestionData from "./questions/oscillations/physical-pendulums.json";
import oscillationsSimpleHarmonicMotionQuestionData from "./questions/oscillations/simple-harmonic-motion.json";
import oscillationsSimplePendulumsQuestionData from "./questions/oscillations/simple-pendulums.json";
import particlesCosmologyAcceleratorsAndDetectorsQuestionData from "./questions/particles-cosmology/accelerators-and-detectors.json";
import particlesCosmologyEarlyUniverseQuestionData from "./questions/particles-cosmology/early-universe.json";
import particlesCosmologyExpandingUniverseQuestionData from "./questions/particles-cosmology/expanding-universe.json";
import particlesCosmologyFundamentalInteractionsQuestionData from "./questions/particles-cosmology/fundamental-interactions.json";
import particlesCosmologyHistoryOfFundamentalParticlesQuestionData from "./questions/particles-cosmology/history-of-fundamental-particles.json";
import particlesCosmologyOpenQuestionsQuestionData from "./questions/particles-cosmology/open-questions.json";
import particlesCosmologyParticleFamiliesQuestionData from "./questions/particles-cosmology/particle-families.json";
import particlesCosmologyQuarksAndGluonsQuestionData from "./questions/particles-cosmology/quarks-and-gluons.json";
import particlesCosmologyStandardModelQuestionData from "./questions/particles-cosmology/standard-model.json";
import photonsComptonScatteringQuestionData from "./questions/photons/compton-scattering.json";
import photonsPairProductionQuestionData from "./questions/photons/pair-production.json";
import photonsPhotoelectricEffectQuestionData from "./questions/photons/photoelectric-effect.json";
import photonsUncertaintyPrincipleQuestionData from "./questions/photons/uncertainty-principle.json";
import photonsWaveParticleDualityQuestionData from "./questions/photons/wave-particle-duality.json";
import photonsXRayProductionQuestionData from "./questions/photons/x-ray-production.json";
import potentialEnergyConservativeForcesQuestionData from "./questions/potential-energy/conservative-forces.json";
import potentialEnergyElasticPotentialEnergyQuestionData from "./questions/potential-energy/elastic-potential-energy.json";
import potentialEnergyForceFromPotentialEnergyQuestionData from "./questions/potential-energy/force-from-potential-energy.json";
import potentialEnergyGravitationalPotentialEnergyQuestionData from "./questions/potential-energy/gravitational-potential-energy.json";
import potentialEnergyNonconservativeForcesQuestionData from "./questions/potential-energy/nonconservative-forces.json";
import potentialEnergyReadingEnergyDiagramsQuestionData from "./questions/potential-energy/reading-energy-diagrams.json";
import quantumWaveFunctionsHarmonicOscillatorQuestionData from "./questions/quantum-wave-functions/harmonic-oscillator.json";
import quantumWaveFunctionsMeasurementInQuantumMechanicsQuestionData from "./questions/quantum-wave-functions/measurement-in-quantum-mechanics.json";
import quantumWaveFunctionsOneDimensionalSchrodingerEquationQuestionData from "./questions/quantum-wave-functions/one-dimensional-schrodinger-equation.json";
import quantumWaveFunctionsParticleInABoxQuestionData from "./questions/quantum-wave-functions/particle-in-a-box.json";
import quantumWaveFunctionsPotentialBarriersAndTunnelingQuestionData from "./questions/quantum-wave-functions/potential-barriers-and-tunneling.json";
import quantumWaveFunctionsPotentialWellsQuestionData from "./questions/quantum-wave-functions/potential-wells.json";
import quantumWaveFunctionsWaveFunctionsQuestionData from "./questions/quantum-wave-functions/wave-functions.json";
import relativityInvarianceOfPhysicalLawsQuestionData from "./questions/relativity/invariance-of-physical-laws.json";
import relativityLengthContractionQuestionData from "./questions/relativity/length-contraction.json";
import relativityLorentzTransformationsQuestionData from "./questions/relativity/lorentz-transformations.json";
import relativityNewtonianLimitsQuestionData from "./questions/relativity/newtonian-limits.json";
import relativityRelativisticDopplerEffectQuestionData from "./questions/relativity/relativistic-doppler-effect.json";
import relativityRelativisticMomentumQuestionData from "./questions/relativity/relativistic-momentum.json";
import relativityRelativisticWorkAndEnergyQuestionData from "./questions/relativity/relativistic-work-and-energy.json";
import relativitySimultaneityQuestionData from "./questions/relativity/simultaneity.json";
import relativityTimeDilationQuestionData from "./questions/relativity/time-dilation.json";
import rigidBodyRotationAngularAccelerationQuestionData from "./questions/rigid-body-rotation/angular-acceleration.json";
import rigidBodyRotationAngularVelocityQuestionData from "./questions/rigid-body-rotation/angular-velocity.json";
import rigidBodyRotationCalculatingMomentsOfInertiaQuestionData from "./questions/rigid-body-rotation/calculating-moments-of-inertia.json";
import rigidBodyRotationConnectingLinearAndAngularMotionQuestionData from "./questions/rigid-body-rotation/connecting-linear-and-angular-motion.json";
import rigidBodyRotationConstantAngularAccelerationQuestionData from "./questions/rigid-body-rotation/constant-angular-acceleration.json";
import rigidBodyRotationParallelAxisTheoremQuestionData from "./questions/rigid-body-rotation/parallel-axis-theorem.json";
import rigidBodyRotationRotationalKineticEnergyQuestionData from "./questions/rigid-body-rotation/rotational-kinetic-energy.json";
import rotationalDynamicsAngularMomentumQuestionData from "./questions/rotational-dynamics/angular-momentum.json";
import rotationalDynamicsConservingAngularMomentumQuestionData from "./questions/rotational-dynamics/conserving-angular-momentum.json";
import rotationalDynamicsGyroscopesAndPrecessionQuestionData from "./questions/rotational-dynamics/gyroscopes-and-precession.json";
import rotationalDynamicsRotationAboutMovingAxesQuestionData from "./questions/rotational-dynamics/rotation-about-moving-axes.json";
import rotationalDynamicsTorqueAndAngularAccelerationQuestionData from "./questions/rotational-dynamics/torque-and-angular-acceleration.json";
import rotationalDynamicsTorqueQuestionData from "./questions/rotational-dynamics/torque.json";
import rotationalDynamicsWorkAndPowerInRotationQuestionData from "./questions/rotational-dynamics/work-and-power-in-rotation.json";
import soundAcousticResonanceQuestionData from "./questions/sound/acoustic-resonance.json";
import soundBeatsQuestionData from "./questions/sound/beats.json";
import soundDopplerShiftsQuestionData from "./questions/sound/doppler-shifts.json";
import soundInterferenceInSoundQuestionData from "./questions/sound/interference-in-sound.json";
import soundShockWavesQuestionData from "./questions/sound/shock-waves.json";
import soundSoundAsAWaveQuestionData from "./questions/sound/sound-as-a-wave.json";
import soundSoundIntensityQuestionData from "./questions/sound/sound-intensity.json";
import soundSpeedOfSoundQuestionData from "./questions/sound/speed-of-sound.json";
import soundStandingSoundWavesQuestionData from "./questions/sound/standing-sound-waves.json";
import temperatureHeatCalorimetryAndPhaseChangeQuestionData from "./questions/temperature-heat/calorimetry-and-phase-change.json";
import temperatureHeatGasThermometersAndAbsoluteTemperatureQuestionData from "./questions/temperature-heat/gas-thermometers-and-absolute-temperature.json";
import temperatureHeatHeatAsEnergyTransferQuestionData from "./questions/temperature-heat/heat-as-energy-transfer.json";
import temperatureHeatHeatTransferMechanismsQuestionData from "./questions/temperature-heat/heat-transfer-mechanisms.json";
import temperatureHeatTemperatureAndThermalEquilibriumQuestionData from "./questions/temperature-heat/temperature-and-thermal-equilibrium.json";
import temperatureHeatTemperatureMeasurementScalesQuestionData from "./questions/temperature-heat/temperature-measurement-scales.json";
import temperatureHeatThermalExpansionQuestionData from "./questions/temperature-heat/thermal-expansion.json";
import workEnergyPowerEnergyTransferWithVariableForcesQuestionData from "./questions/work-energy-power/energy-transfer-with-variable-forces.json";
import workEnergyPowerKineticEnergyAndTheWorkEnergyPrincipleQuestionData from "./questions/work-energy-power/kinetic-energy-and-the-work-energy-principle.json";
import workEnergyPowerPowerAndRateOfWorkQuestionData from "./questions/work-energy-power/power-and-rate-of-work.json";
import workEnergyPowerWorkByAForceQuestionData from "./questions/work-energy-power/work-by-a-force.json";

export const level1PhysicsQuestionTopics = [
  alternatingCurrentLrcSeriesCircuitsInAcQuestionData,
  alternatingCurrentPhasorsAndAcSignalsQuestionData,
  alternatingCurrentPowerInAcCircuitsQuestionData,
  alternatingCurrentResistanceAndReactanceQuestionData,
  alternatingCurrentResonanceInAcCircuitsQuestionData,
  alternatingCurrentTransformersQuestionData,
  applyingForceModelsDynamicsOfCircularMotionQuestionData,
  applyingForceModelsEquilibriumWithNewtonsFirstLawQuestionData,
  applyingForceModelsFourFundamentalInteractionsQuestionData,
  applyingForceModelsParticleDynamicsWithNewtonsSecondLawQuestionData,
  applyingForceModelsStaticAndKineticFrictionQuestionData,
  atomicQuantumStructureElectronSpinQuestionData,
  atomicQuantumStructureExclusionPrincipleQuestionData,
  atomicQuantumStructureHydrogenAtomQuestionData,
  atomicQuantumStructureManyElectronAtomsQuestionData,
  atomicQuantumStructureParticleInAThreeDimensionalBoxQuestionData,
  atomicQuantumStructureQuantumEntanglementQuestionData,
  atomicQuantumStructureThreeDimensionalSchrodingerEquationQuestionData,
  atomicQuantumStructureXRaySpectraQuestionData,
  atomicQuantumStructureZeemanEffectQuestionData,
  capacitorsDielectricsCapacitanceQuestionData,
  capacitorsDielectricsDielectricsQuestionData,
  capacitorsDielectricsGaussSLawInMaterialsQuestionData,
  capacitorsDielectricsMolecularViewOfInducedChargeQuestionData,
  capacitorsDielectricsSeriesAndParallelCapacitorsQuestionData,
  capacitorsDielectricsStoredEnergyAndFieldEnergyQuestionData,
  currentResistanceElectricCurrentQuestionData,
  currentResistanceElectricPowerQuestionData,
  currentResistanceEmfAndCircuitModelsQuestionData,
  currentResistanceMicroscopicModelOfConductionQuestionData,
  currentResistanceResistanceQuestionData,
  currentResistanceResistivityQuestionData,
  dcCircuitsElectricalMetersQuestionData,
  dcCircuitsKirchhoffAnalysisQuestionData,
  dcCircuitsPowerDistributionQuestionData,
  dcCircuitsRcTransientsQuestionData,
  dcCircuitsSeriesAndParallelResistorNetworksQuestionData,
  diffractionCircularAperturesAndResolutionQuestionData,
  diffractionDiffractionGratingsQuestionData,
  diffractionFresnelAndFraunhoferRegimesQuestionData,
  diffractionHolographyQuestionData,
  diffractionIntensityInSingleSlitPatternsQuestionData,
  diffractionMultipleSlitPatternsQuestionData,
  diffractionSingleSlitDiffractionQuestionData,
  diffractionXRayDiffractionQuestionData,
  electricChargeFieldsCalculatingElectricFieldsQuestionData,
  electricChargeFieldsChargeInductionQuestionData,
  electricChargeFieldsConductorsAndInsulatorsQuestionData,
  electricChargeFieldsCoulombForcesQuestionData,
  electricChargeFieldsElectricChargeQuestionData,
  electricChargeFieldsElectricDipolesQuestionData,
  electricChargeFieldsElectricFieldsAndForcesQuestionData,
  electricChargeFieldsFieldLineRepresentationsQuestionData,
  electricPotentialCalculatingPotentialQuestionData,
  electricPotentialElectricPotentialEnergyQuestionData,
  electricPotentialElectricPotentialQuestionData,
  electricPotentialEquipotentialSurfacesQuestionData,
  electricPotentialPotentialGradientsQuestionData,
  electromagneticInductionDisplacementCurrentQuestionData,
  electromagneticInductionEddyCurrentsQuestionData,
  electromagneticInductionFaradaySLawQuestionData,
  electromagneticInductionInducedElectricFieldsQuestionData,
  electromagneticInductionInductionObservationsQuestionData,
  electromagneticInductionLenzSLawQuestionData,
  electromagneticInductionMaxwellSEquationsQuestionData,
  electromagneticInductionMotionalEmfQuestionData,
  electromagneticInductionSuperconductivityQuestionData,
  electromagneticWavesEnergyAndMomentumInElectromagneticWavesQuestionData,
  electromagneticWavesMaxwellSEquationsToWavesQuestionData,
  electromagneticWavesPlaneWavesAndLightSpeedQuestionData,
  electromagneticWavesSinusoidalElectromagneticWavesQuestionData,
  electromagneticWavesStandingElectromagneticWavesQuestionData,
  entropyHeatEnginesEntropyQuestionData,
  equilibriumMaterialsCenterOfGravityQuestionData,
  equilibriumMaterialsConditionsForStaticEquilibriumQuestionData,
  equilibriumMaterialsElasticModuliQuestionData,
  equilibriumMaterialsElasticVersusPlasticBehaviorQuestionData,
  equilibriumMaterialsSolvingRigidBodyEquilibriumQuestionData,
  equilibriumMaterialsStressAndStrainQuestionData,
  firstLawThermodynamicsAdiabaticIdealGasProcessesQuestionData,
  firstLawThermodynamicsCommonThermodynamicProcessesQuestionData,
  firstLawThermodynamicsHeatCapacityOfIdealGasesQuestionData,
  firstLawThermodynamicsInternalEnergyAndTheFirstLawQuestionData,
  firstLawThermodynamicsInternalEnergyOfIdealGasesQuestionData,
  firstLawThermodynamicsPathsBetweenStatesQuestionData,
  firstLawThermodynamicsThermodynamicSystemsQuestionData,
  firstLawThermodynamicsWorkDuringVolumeChangesQuestionData,
  fluidsBernoulliModelsQuestionData,
  fluidsBuoyancyQuestionData,
  fluidsDensityInGasesAndLiquidsQuestionData,
  fluidsFluidFlowQuestionData,
  fluidsPressureInFluidsQuestionData,
  fluidsViscosityAndTurbulenceQuestionData,
  forcesNewtonsLawsActionReactionPairsQuestionData,
  forcesNewtonsLawsDrawingForceDiagramsQuestionData,
  forcesNewtonsLawsEquilibriumAndInertiaQuestionData,
  forcesNewtonsLawsForceMassAndAccelerationQuestionData,
  forcesNewtonsLawsForcesAsInteractionsQuestionData,
  forcesNewtonsLawsWeightVersusMassQuestionData,
  gausssLawChargeAndElectricFluxQuestionData,
  gausssLawChargeOnConductorsQuestionData,
  gausssLawComputingElectricFluxQuestionData,
  gausssLawGaussSLawQuestionData,
  gausssLawSymmetryApplicationsOfGaussSLawQuestionData,
  geometricOpticsCamerasQuestionData,
  geometricOpticsMagnifiersQuestionData,
  geometricOpticsMicroscopesQuestionData,
  geometricOpticsPlaneSurfaceReflectionQuestionData,
  geometricOpticsPlaneSurfaceRefractionQuestionData,
  geometricOpticsSphericalMirrorsQuestionData,
  geometricOpticsSphericalRefractionQuestionData,
  geometricOpticsTelescopesQuestionData,
  geometricOpticsTheEyeQuestionData,
  geometricOpticsThinLensesQuestionData,
  gravitationApparentWeightOnEarthQuestionData,
  gravitationBlackHolesQuestionData,
  gravitationFieldsFromSphericalMassesQuestionData,
  gravitationKeplerModelsOfOrbitsQuestionData,
  gravitationSatelliteMotionQuestionData,
  gravitationUniversalGravitationQuestionData,
  gravitationWeightInGravitationalFieldsQuestionData,
  inductanceLcOscillationsQuestionData,
  inductanceLrcSeriesCircuitsQuestionData,
  inductanceMagneticFieldEnergyQuestionData,
  inductanceMutualInductanceQuestionData,
  inductanceRlTransientsQuestionData,
  inductanceSelfInductanceAndInductorsQuestionData,
  interferenceCoherenceAndInterferenceQuestionData,
  interferenceIntensityInInterferencePatternsQuestionData,
  interferenceMichelsonInterferometerQuestionData,
  interferenceThinFilmInterferenceQuestionData,
  interferenceTwoSourceLightInterferenceQuestionData,
  lightPropagationDispersionQuestionData,
  lightPropagationHuygensPrincipleQuestionData,
  lightPropagationNatureOfLightQuestionData,
  lightPropagationPolarizationQuestionData,
  lightPropagationReflectionAndRefractionQuestionData,
  lightPropagationScatteringQuestionData,
  lightPropagationTotalInternalReflectionQuestionData,
  magneticFieldSourcesAmpereSLawQuestionData,
  magneticFieldSourcesBiotSavartForCurrentElementsQuestionData,
  magneticFieldSourcesFieldsAroundStraightCurrentsQuestionData,
  magneticFieldSourcesFieldsFromCurrentLoopsQuestionData,
  magneticFieldSourcesFieldsFromMovingChargesQuestionData,
  magneticFieldSourcesForcesBetweenParallelCurrentsQuestionData,
  magneticFieldSourcesMagneticMaterialsQuestionData,
  magneticFieldSourcesSymmetryApplicationsOfAmpereSLawQuestionData,
  magneticFieldsForcesChargedParticlesInMagneticFieldsQuestionData,
  magneticFieldsForcesDcMotorsQuestionData,
  magneticFieldsForcesForcesOnCurrentCarryingConductorsQuestionData,
  magneticFieldsForcesHallEffectQuestionData,
  magneticFieldsForcesMagneticFieldLinesQuestionData,
  magneticFieldsForcesMagneticFieldsQuestionData,
  magneticFieldsForcesMagneticFluxQuestionData,
  magneticFieldsForcesMagnetismBasicsQuestionData,
  magneticFieldsForcesParticleMotionApplicationsQuestionData,
  magneticFieldsForcesTorqueOnCurrentLoopsQuestionData,
  matterThermalScaleEquationsOfStateQuestionData,
  matterThermalScaleHeatCapacityQuestionData,
  matterThermalScaleIdealGasModelQuestionData,
  matterThermalScaleMolecularPropertiesOfMatterQuestionData,
  matterThermalScaleMolecularSpeedsQuestionData,
  matterThermalScalePhasesOfMatterQuestionData,
  matterWavesAtomicSpectraQuestionData,
  matterWavesBohrEnergyLevelsQuestionData,
  matterWavesContinuousSpectraQuestionData,
  matterWavesElectronWavesQuestionData,
  matterWavesLasersQuestionData,
  matterWavesNuclearAtomQuestionData,
  matterWavesUncertaintyRevisitedQuestionData,
  measurementVectorsAReliableProblemSolvingProcessQuestionData,
  measurementVectorsAddingVectorsGeometricallyQuestionData,
  measurementVectorsDotAndCrossProductsQuestionData,
  measurementVectorsEstimationAndScaleSenseQuestionData,
  measurementVectorsHowPhysicsBuildsModelsQuestionData,
  measurementVectorsMeasurementUncertaintyQuestionData,
  measurementVectorsResolvingVectorsIntoComponentsQuestionData,
  measurementVectorsSignificantFiguresQuestionData,
  measurementVectorsUnitConversionWithoutGuessworkQuestionData,
  measurementVectorsUnitVectorNotationQuestionData,
  measurementVectorsUnitsAndMeasurementStandardsQuestionData,
  mechanicalWavesBoundaryConditionsQuestionData,
  mechanicalWavesEnergyTransportInWavesQuestionData,
  mechanicalWavesMathematicalWaveDescriptionsQuestionData,
  mechanicalWavesPeriodicWavePatternsQuestionData,
  mechanicalWavesSpeedOfTransverseWavesQuestionData,
  mechanicalWavesStandingWavesOnStringsQuestionData,
  mechanicalWavesStringNormalModesQuestionData,
  mechanicalWavesSuperpositionQuestionData,
  mechanicalWavesTypesOfMechanicalWavesQuestionData,
  momentumSystemsCenterOfMassQuestionData,
  momentumSystemsCollisionsAsMomentumProblemsQuestionData,
  momentumSystemsElasticCollisionModelsQuestionData,
  momentumSystemsMomentumAndImpulseQuestionData,
  momentumSystemsMomentumConservationQuestionData,
  momentumSystemsRocketMotionQuestionData,
  motionInSpaceAccelerationVectorsQuestionData,
  motionInSpaceCircularMotionKinematicsQuestionData,
  motionInSpacePositionAndVelocityVectorsQuestionData,
  motionInSpaceProjectileModelsQuestionData,
  motionInSpaceRelativeMotionQuestionData,
  nuclearPhysicsActivityAndHalfLifeQuestionData,
  nuclearPhysicsBindingEnergyQuestionData,
  nuclearPhysicsBiologicalEffectsOfRadiationQuestionData,
  nuclearPhysicsFissionQuestionData,
  nuclearPhysicsFusionQuestionData,
  nuclearPhysicsNuclearPropertiesQuestionData,
  nuclearPhysicsNuclearReactionsQuestionData,
  nuclearPhysicsNuclearStabilityQuestionData,
  nuclearPhysicsNuclearStructureQuestionData,
  nuclearPhysicsRadioactivityQuestionData,
  oneDimensionalMotionAccelerationAsARateOfChangeQuestionData,
  oneDimensionalMotionAverageVelocityQuestionData,
  oneDimensionalMotionConstantAccelerationModelsQuestionData,
  oneDimensionalMotionFreeFallMotionQuestionData,
  oneDimensionalMotionInstantaneousVelocityQuestionData,
  oneDimensionalMotionPositionAndTimeQuestionData,
  oneDimensionalMotionPositionAndVelocityFromCalculusQuestionData,
  oscillationsApplicationsOfHarmonicMotionQuestionData,
  oscillationsDampingQuestionData,
  oscillationsDescribingOscillationQuestionData,
  oscillationsDrivenOscillationsAndResonanceQuestionData,
  oscillationsEnergyInOscillatorsQuestionData,
  oscillationsPhysicalPendulumsQuestionData,
  oscillationsSimpleHarmonicMotionQuestionData,
  oscillationsSimplePendulumsQuestionData,
  particlesCosmologyAcceleratorsAndDetectorsQuestionData,
  particlesCosmologyEarlyUniverseQuestionData,
  particlesCosmologyExpandingUniverseQuestionData,
  particlesCosmologyFundamentalInteractionsQuestionData,
  particlesCosmologyHistoryOfFundamentalParticlesQuestionData,
  particlesCosmologyOpenQuestionsQuestionData,
  particlesCosmologyParticleFamiliesQuestionData,
  particlesCosmologyQuarksAndGluonsQuestionData,
  particlesCosmologyStandardModelQuestionData,
  photonsComptonScatteringQuestionData,
  photonsPairProductionQuestionData,
  photonsPhotoelectricEffectQuestionData,
  photonsUncertaintyPrincipleQuestionData,
  photonsWaveParticleDualityQuestionData,
  photonsXRayProductionQuestionData,
  potentialEnergyConservativeForcesQuestionData,
  potentialEnergyElasticPotentialEnergyQuestionData,
  potentialEnergyForceFromPotentialEnergyQuestionData,
  potentialEnergyGravitationalPotentialEnergyQuestionData,
  potentialEnergyNonconservativeForcesQuestionData,
  potentialEnergyReadingEnergyDiagramsQuestionData,
  quantumWaveFunctionsHarmonicOscillatorQuestionData,
  quantumWaveFunctionsMeasurementInQuantumMechanicsQuestionData,
  quantumWaveFunctionsOneDimensionalSchrodingerEquationQuestionData,
  quantumWaveFunctionsParticleInABoxQuestionData,
  quantumWaveFunctionsPotentialBarriersAndTunnelingQuestionData,
  quantumWaveFunctionsPotentialWellsQuestionData,
  quantumWaveFunctionsWaveFunctionsQuestionData,
  relativityInvarianceOfPhysicalLawsQuestionData,
  relativityLengthContractionQuestionData,
  relativityLorentzTransformationsQuestionData,
  relativityNewtonianLimitsQuestionData,
  relativityRelativisticDopplerEffectQuestionData,
  relativityRelativisticMomentumQuestionData,
  relativityRelativisticWorkAndEnergyQuestionData,
  relativitySimultaneityQuestionData,
  relativityTimeDilationQuestionData,
  rigidBodyRotationAngularAccelerationQuestionData,
  rigidBodyRotationAngularVelocityQuestionData,
  rigidBodyRotationCalculatingMomentsOfInertiaQuestionData,
  rigidBodyRotationConnectingLinearAndAngularMotionQuestionData,
  rigidBodyRotationConstantAngularAccelerationQuestionData,
  rigidBodyRotationParallelAxisTheoremQuestionData,
  rigidBodyRotationRotationalKineticEnergyQuestionData,
  rotationalDynamicsAngularMomentumQuestionData,
  rotationalDynamicsConservingAngularMomentumQuestionData,
  rotationalDynamicsGyroscopesAndPrecessionQuestionData,
  rotationalDynamicsRotationAboutMovingAxesQuestionData,
  rotationalDynamicsTorqueAndAngularAccelerationQuestionData,
  rotationalDynamicsTorqueQuestionData,
  rotationalDynamicsWorkAndPowerInRotationQuestionData,
  soundAcousticResonanceQuestionData,
  soundBeatsQuestionData,
  soundDopplerShiftsQuestionData,
  soundInterferenceInSoundQuestionData,
  soundShockWavesQuestionData,
  soundSoundAsAWaveQuestionData,
  soundSoundIntensityQuestionData,
  soundSpeedOfSoundQuestionData,
  soundStandingSoundWavesQuestionData,
  temperatureHeatCalorimetryAndPhaseChangeQuestionData,
  temperatureHeatGasThermometersAndAbsoluteTemperatureQuestionData,
  temperatureHeatHeatAsEnergyTransferQuestionData,
  temperatureHeatHeatTransferMechanismsQuestionData,
  temperatureHeatTemperatureAndThermalEquilibriumQuestionData,
  temperatureHeatTemperatureMeasurementScalesQuestionData,
  temperatureHeatThermalExpansionQuestionData,
  workEnergyPowerEnergyTransferWithVariableForcesQuestionData,
  workEnergyPowerKineticEnergyAndTheWorkEnergyPrincipleQuestionData,
  workEnergyPowerPowerAndRateOfWorkQuestionData,
  workEnergyPowerWorkByAForceQuestionData,
] as const;
