/* This file is generated by apps/academy/scripts/generate-question-registry.mjs. */
/* Do not edit manually. */

import applicationsOfDerivativesCurveSketchingQuestionData from "./questions/applications-of-derivatives/curve-sketching.json";
import applicationsOfDerivativesLHopitalSRuleQuestionData from "./questions/applications-of-derivatives/l-hopital-s-rule.json";
import applicationsOfDerivativesLinearApproximationQuestionData from "./questions/applications-of-derivatives/linear-approximation.json";
import applicationsOfDerivativesOptimisationQuestionData from "./questions/applications-of-derivatives/optimisation.json";
import applicationsOfDerivativesRelatedRatesQuestionData from "./questions/applications-of-derivatives/related-rates.json";
import applicationsOfIntegralsArcLengthQuestionData from "./questions/applications-of-integrals/arc-length.json";
import applicationsOfIntegralsAreasBetweenCurvesQuestionData from "./questions/applications-of-integrals/areas-between-curves.json";
import applicationsOfIntegralsVolumesQuestionData from "./questions/applications-of-integrals/volumes.json";
import differentialCalculusChainRuleQuestionData from "./questions/differential-calculus/chain-rule.json";
import differentialCalculusDerivativeFromFirstPrinciplesQuestionData from "./questions/differential-calculus/derivative-from-first-principles.json";
import differentialCalculusDifferentiationRulesQuestionData from "./questions/differential-calculus/differentiation-rules.json";
import differentialCalculusHigherDerivativesQuestionData from "./questions/differential-calculus/higher-derivatives.json";
import differentialCalculusImplicitDifferentiationQuestionData from "./questions/differential-calculus/implicit-differentiation.json";
import differentialEquationsFirstOrderDifferentialEquationsQuestionData from "./questions/differential-equations/first-order-differential-equations.json";
import differentialEquationsSecondOrderDifferentialEquationsQuestionData from "./questions/differential-equations/second-order-differential-equations.json";
import differentialEquationsSeparationOfVariablesQuestionData from "./questions/differential-equations/separation-of-variables.json";
import differentialEquationsSeriesSolutionsQuestionData from "./questions/differential-equations/series-solutions.json";
import foundationsAndLimitsAsymptoticBehaviourQuestionData from "./questions/foundations-and-limits/asymptotic-behaviour.json";
import foundationsAndLimitsContinuityQuestionData from "./questions/foundations-and-limits/continuity.json";
import foundationsAndLimitsFunctionsAndGraphsQuestionData from "./questions/foundations-and-limits/functions-and-graphs.json";
import foundationsAndLimitsInfiniteLimitsQuestionData from "./questions/foundations-and-limits/infinite-limits.json";
import foundationsAndLimitsLimitLawsQuestionData from "./questions/foundations-and-limits/limit-laws.json";
import integralCalculusAntiderivativesQuestionData from "./questions/integral-calculus/antiderivatives.json";
import integralCalculusDefiniteIntegralsQuestionData from "./questions/integral-calculus/definite-integrals.json";
import integralCalculusFundamentalTheoremOfCalculusQuestionData from "./questions/integral-calculus/fundamental-theorem-of-calculus.json";
import integralCalculusImproperIntegralsQuestionData from "./questions/integral-calculus/improper-integrals.json";
import integralCalculusIntegrationByPartsQuestionData from "./questions/integral-calculus/integration-by-parts.json";
import integralCalculusPartialFractionsQuestionData from "./questions/integral-calculus/partial-fractions.json";
import integralCalculusSubstitutionQuestionData from "./questions/integral-calculus/substitution.json";
import seriesAndApproximationsConvergenceTestsQuestionData from "./questions/series-and-approximations/convergence-tests.json";
import seriesAndApproximationsFourierSeriesQuestionData from "./questions/series-and-approximations/fourier-series.json";
import seriesAndApproximationsPowerSeriesQuestionData from "./questions/series-and-approximations/power-series.json";
import seriesAndApproximationsSequencesQuestionData from "./questions/series-and-approximations/sequences.json";
import seriesAndApproximationsSeriesQuestionData from "./questions/series-and-approximations/series.json";
import seriesAndApproximationsTaylorSeriesQuestionData from "./questions/series-and-approximations/taylor-series.json";
import severalVariableCalculusCoordinateChangesQuestionData from "./questions/several-variable-calculus/coordinate-changes.json";
import severalVariableCalculusCriticalPointsQuestionData from "./questions/several-variable-calculus/critical-points.json";
import severalVariableCalculusGradientQuestionData from "./questions/several-variable-calculus/gradient.json";
import severalVariableCalculusMultipleIntegralsQuestionData from "./questions/several-variable-calculus/multiple-integrals.json";
import severalVariableCalculusMultivariableChainRuleQuestionData from "./questions/several-variable-calculus/multivariable-chain-rule.json";
import severalVariableCalculusMultivariableFunctionsQuestionData from "./questions/several-variable-calculus/multivariable-functions.json";
import severalVariableCalculusPartialDerivativesQuestionData from "./questions/several-variable-calculus/partial-derivatives.json";

export const level1CalculusQuestionTopics = [
  applicationsOfDerivativesCurveSketchingQuestionData,
  applicationsOfDerivativesLHopitalSRuleQuestionData,
  applicationsOfDerivativesLinearApproximationQuestionData,
  applicationsOfDerivativesOptimisationQuestionData,
  applicationsOfDerivativesRelatedRatesQuestionData,
  applicationsOfIntegralsArcLengthQuestionData,
  applicationsOfIntegralsAreasBetweenCurvesQuestionData,
  applicationsOfIntegralsVolumesQuestionData,
  differentialCalculusChainRuleQuestionData,
  differentialCalculusDerivativeFromFirstPrinciplesQuestionData,
  differentialCalculusDifferentiationRulesQuestionData,
  differentialCalculusHigherDerivativesQuestionData,
  differentialCalculusImplicitDifferentiationQuestionData,
  differentialEquationsFirstOrderDifferentialEquationsQuestionData,
  differentialEquationsSecondOrderDifferentialEquationsQuestionData,
  differentialEquationsSeparationOfVariablesQuestionData,
  differentialEquationsSeriesSolutionsQuestionData,
  foundationsAndLimitsAsymptoticBehaviourQuestionData,
  foundationsAndLimitsContinuityQuestionData,
  foundationsAndLimitsFunctionsAndGraphsQuestionData,
  foundationsAndLimitsInfiniteLimitsQuestionData,
  foundationsAndLimitsLimitLawsQuestionData,
  integralCalculusAntiderivativesQuestionData,
  integralCalculusDefiniteIntegralsQuestionData,
  integralCalculusFundamentalTheoremOfCalculusQuestionData,
  integralCalculusImproperIntegralsQuestionData,
  integralCalculusIntegrationByPartsQuestionData,
  integralCalculusPartialFractionsQuestionData,
  integralCalculusSubstitutionQuestionData,
  seriesAndApproximationsConvergenceTestsQuestionData,
  seriesAndApproximationsFourierSeriesQuestionData,
  seriesAndApproximationsPowerSeriesQuestionData,
  seriesAndApproximationsSequencesQuestionData,
  seriesAndApproximationsSeriesQuestionData,
  seriesAndApproximationsTaylorSeriesQuestionData,
  severalVariableCalculusCoordinateChangesQuestionData,
  severalVariableCalculusCriticalPointsQuestionData,
  severalVariableCalculusGradientQuestionData,
  severalVariableCalculusMultipleIntegralsQuestionData,
  severalVariableCalculusMultivariableChainRuleQuestionData,
  severalVariableCalculusMultivariableFunctionsQuestionData,
  severalVariableCalculusPartialDerivativesQuestionData,
] as const;
