/* This file is generated by apps/academy/scripts/generate-question-registry.mjs. */
/* Do not edit manually. */

import determinantsAdjugateMatrixQuestionData from "./questions/determinants/adjugate-matrix.json";
import determinantsCramerSRuleQuestionData from "./questions/determinants/cramer-s-rule.json";
import determinantsDeterminantCalculationsQuestionData from "./questions/determinants/determinant-calculations.json";
import determinantsDeterminantPropertiesQuestionData from "./questions/determinants/determinant-properties.json";
import determinantsDeterminantsAndGeometryQuestionData from "./questions/determinants/determinants-and-geometry.json";
import determinantsDeterminantsAndInvertibilityQuestionData from "./questions/determinants/determinants-and-invertibility.json";
import determinantsGeneralDeterminantQuestionData from "./questions/determinants/general-determinant.json";
import determinantsSmallDeterminantsQuestionData from "./questions/determinants/small-determinants.json";
import linearMapsChangeOfBasisQuestionData from "./questions/linear-maps/change-of-basis.json";
import linearMapsChangeOfCoordinatesQuestionData from "./questions/linear-maps/change-of-coordinates.json";
import linearMapsImageAndKernelQuestionData from "./questions/linear-maps/image-and-kernel.json";
import linearMapsIsomorphismsQuestionData from "./questions/linear-maps/isomorphisms.json";
import linearMapsLinearMapExamplesQuestionData from "./questions/linear-maps/linear-map-examples.json";
import linearMapsLinearMapsQuestionData from "./questions/linear-maps/linear-maps.json";
import linearMapsMatrixRepresentationsQuestionData from "./questions/linear-maps/matrix-representations.json";
import linearMapsRankAndNullityQuestionData from "./questions/linear-maps/rank-and-nullity.json";
import linearSystemsAugmentedMatricesQuestionData from "./questions/linear-systems/augmented-matrices.json";
import linearSystemsEchelonFormQuestionData from "./questions/linear-systems/echelon-form.json";
import linearSystemsElementaryRowOperationsQuestionData from "./questions/linear-systems/elementary-row-operations.json";
import linearSystemsGaussJordanEliminationQuestionData from "./questions/linear-systems/gauss-jordan-elimination.json";
import linearSystemsInverseComputationQuestionData from "./questions/linear-systems/inverse-computation.json";
import linearSystemsInvertibleMatrixTheoremQuestionData from "./questions/linear-systems/invertible-matrix-theorem.json";
import linearSystemsReducedRowEchelonFormQuestionData from "./questions/linear-systems/reduced-row-echelon-form.json";
import linearSystemsSolutionSetsQuestionData from "./questions/linear-systems/solution-sets.json";
import matrixAlgebraIdentityAndZeroMatricesQuestionData from "./questions/matrix-algebra/identity-and-zero-matrices.json";
import matrixAlgebraInverseMatricesQuestionData from "./questions/matrix-algebra/inverse-matrices.json";
import matrixAlgebraMatrixAdditionQuestionData from "./questions/matrix-algebra/matrix-addition.json";
import matrixAlgebraMatrixMultiplicationQuestionData from "./questions/matrix-algebra/matrix-multiplication.json";
import matrixAlgebraMatrixNotationQuestionData from "./questions/matrix-algebra/matrix-notation.json";
import matrixAlgebraScalarMultiplicationQuestionData from "./questions/matrix-algebra/scalar-multiplication.json";
import matrixAlgebraTransposeQuestionData from "./questions/matrix-algebra/transpose.json";
import realVectorSpacesAbstractBasesQuestionData from "./questions/real-vector-spaces/abstract-bases.json";
import realVectorSpacesAbstractDimensionQuestionData from "./questions/real-vector-spaces/abstract-dimension.json";
import realVectorSpacesCoordinatesQuestionData from "./questions/real-vector-spaces/coordinates.json";
import realVectorSpacesRealVectorSpacesQuestionData from "./questions/real-vector-spaces/real-vector-spaces.json";
import realVectorSpacesSumsAndIntersectionsQuestionData from "./questions/real-vector-spaces/sums-and-intersections.json";
import realVectorSpacesVectorSubspacesQuestionData from "./questions/real-vector-spaces/vector-subspaces.json";
import subspacesAndDimensionBasesInRnQuestionData from "./questions/subspaces-and-dimension/bases-in-rn.json";
import subspacesAndDimensionDimensionInRnQuestionData from "./questions/subspaces-and-dimension/dimension-in-rn.json";
import subspacesAndDimensionLinearIndependenceQuestionData from "./questions/subspaces-and-dimension/linear-independence.json";
import subspacesAndDimensionSpanningSetsQuestionData from "./questions/subspaces-and-dimension/spanning-sets.json";
import subspacesAndDimensionSubspacesOfRnQuestionData from "./questions/subspaces-and-dimension/subspaces-of-rn.json";
import vectorsInRnAnglesAndOrthogonalityQuestionData from "./questions/vectors-in-rn/angles-and-orthogonality.json";
import vectorsInRnLinesInR3QuestionData from "./questions/vectors-in-rn/lines-in-r3.json";
import vectorsInRnNormsAndDistancesQuestionData from "./questions/vectors-in-rn/norms-and-distances.json";
import vectorsInRnPlanesInR3QuestionData from "./questions/vectors-in-rn/planes-in-r3.json";
import vectorsInRnScalarProductQuestionData from "./questions/vectors-in-rn/scalar-product.json";
import vectorsInRnScalarTripleProductQuestionData from "./questions/vectors-in-rn/scalar-triple-product.json";
import vectorsInRnThreeByThreeSystemsQuestionData from "./questions/vectors-in-rn/three-by-three-systems.json";
import vectorsInRnVectorOperationsQuestionData from "./questions/vectors-in-rn/vector-operations.json";
import vectorsInRnVectorProductQuestionData from "./questions/vectors-in-rn/vector-product.json";
import vectorsInRnVectorsInRnQuestionData from "./questions/vectors-in-rn/vectors-in-rn.json";

export const level1LinearAlgebraQuestionTopics = [
  determinantsAdjugateMatrixQuestionData,
  determinantsCramerSRuleQuestionData,
  determinantsDeterminantCalculationsQuestionData,
  determinantsDeterminantPropertiesQuestionData,
  determinantsDeterminantsAndGeometryQuestionData,
  determinantsDeterminantsAndInvertibilityQuestionData,
  determinantsGeneralDeterminantQuestionData,
  determinantsSmallDeterminantsQuestionData,
  linearMapsChangeOfBasisQuestionData,
  linearMapsChangeOfCoordinatesQuestionData,
  linearMapsImageAndKernelQuestionData,
  linearMapsIsomorphismsQuestionData,
  linearMapsLinearMapExamplesQuestionData,
  linearMapsLinearMapsQuestionData,
  linearMapsMatrixRepresentationsQuestionData,
  linearMapsRankAndNullityQuestionData,
  linearSystemsAugmentedMatricesQuestionData,
  linearSystemsEchelonFormQuestionData,
  linearSystemsElementaryRowOperationsQuestionData,
  linearSystemsGaussJordanEliminationQuestionData,
  linearSystemsInverseComputationQuestionData,
  linearSystemsInvertibleMatrixTheoremQuestionData,
  linearSystemsReducedRowEchelonFormQuestionData,
  linearSystemsSolutionSetsQuestionData,
  matrixAlgebraIdentityAndZeroMatricesQuestionData,
  matrixAlgebraInverseMatricesQuestionData,
  matrixAlgebraMatrixAdditionQuestionData,
  matrixAlgebraMatrixMultiplicationQuestionData,
  matrixAlgebraMatrixNotationQuestionData,
  matrixAlgebraScalarMultiplicationQuestionData,
  matrixAlgebraTransposeQuestionData,
  realVectorSpacesAbstractBasesQuestionData,
  realVectorSpacesAbstractDimensionQuestionData,
  realVectorSpacesCoordinatesQuestionData,
  realVectorSpacesRealVectorSpacesQuestionData,
  realVectorSpacesSumsAndIntersectionsQuestionData,
  realVectorSpacesVectorSubspacesQuestionData,
  subspacesAndDimensionBasesInRnQuestionData,
  subspacesAndDimensionDimensionInRnQuestionData,
  subspacesAndDimensionLinearIndependenceQuestionData,
  subspacesAndDimensionSpanningSetsQuestionData,
  subspacesAndDimensionSubspacesOfRnQuestionData,
  vectorsInRnAnglesAndOrthogonalityQuestionData,
  vectorsInRnLinesInR3QuestionData,
  vectorsInRnNormsAndDistancesQuestionData,
  vectorsInRnPlanesInR3QuestionData,
  vectorsInRnScalarProductQuestionData,
  vectorsInRnScalarTripleProductQuestionData,
  vectorsInRnThreeByThreeSystemsQuestionData,
  vectorsInRnVectorOperationsQuestionData,
  vectorsInRnVectorProductQuestionData,
  vectorsInRnVectorsInRnQuestionData,
] as const;
