/* This file is generated by apps/academy/scripts/generate-question-registry.mjs. */
/* Do not edit manually. */

import differentiationChainRuleQuestionData from "./questions/differentiation/chain-rule.json";
import differentiationDerivativesQuestionData from "./questions/differentiation/derivatives.json";
import differentiationFirstPrinciplesQuestionData from "./questions/differentiation/first-principles.json";
import differentiationHigherOrderDerivativesQuestionData from "./questions/differentiation/higher-order-derivatives.json";
import differentiationImplicitDifferentiationQuestionData from "./questions/differentiation/implicit-differentiation.json";
import differentiationInverseDerivativesQuestionData from "./questions/differentiation/inverse-derivatives.json";
import differentiationLhopitalsRuleQuestionData from "./questions/differentiation/lhopitals-rule.json";
import differentiationProductRuleQuestionData from "./questions/differentiation/product-rule.json";
import differentiationQuotientRuleQuestionData from "./questions/differentiation/quotient-rule.json";
import differentiationStandardDerivativesQuestionData from "./questions/differentiation/standard-derivatives.json";
import functionsFunctionsQuestionData from "./questions/functions/functions.json";
import functionsInverseFunctionsQuestionData from "./questions/functions/inverse-functions.json";
import integrationAntiderivativesQuestionData from "./questions/integration/antiderivatives.json";
import integrationCoverUpRuleQuestionData from "./questions/integration/cover-up-rule.json";
import integrationDefiniteIntegralsQuestionData from "./questions/integration/definite-integrals.json";
import integrationFundamentalTheoremQuestionData from "./questions/integration/fundamental-theorem.json";
import integrationIntegrationByPartsQuestionData from "./questions/integration/integration-by-parts.json";
import integrationPartialFractionsQuestionData from "./questions/integration/partial-fractions.json";
import integrationPolynomialDivisionQuestionData from "./questions/integration/polynomial-division.json";
import integrationRationalIntegralsQuestionData from "./questions/integration/rational-integrals.json";
import integrationReverseDifferentiationQuestionData from "./questions/integration/reverse-differentiation.json";
import integrationStandardIntegralsQuestionData from "./questions/integration/standard-integrals.json";
import integrationSubstitutionQuestionData from "./questions/integration/substitution.json";
import integrationTrigPowerIntegralsQuestionData from "./questions/integration/trig-power-integrals.json";
import limitsAlgebraicLimitsQuestionData from "./questions/limits/algebraic-limits.json";
import limitsChangeOfVariablesQuestionData from "./questions/limits/change-of-variables.json";
import limitsContinuityQuestionData from "./questions/limits/continuity.json";
import limitsFormalLimitsQuestionData from "./questions/limits/formal-limits.json";
import limitsLimitLawsQuestionData from "./questions/limits/limit-laws.json";
import limitsLimitVariationsQuestionData from "./questions/limits/limit-variations.json";
import limitsSineLimitQuestionData from "./questions/limits/sine-limit.json";
import limitsSqueezeTheoremQuestionData from "./questions/limits/squeeze-theorem.json";
import realNumbersAlgebraicManipulationQuestionData from "./questions/real-numbers/algebraic-manipulation.json";
import realNumbersBinomialCoefficientsQuestionData from "./questions/real-numbers/binomial-coefficients.json";
import realNumbersBinomialTheoremQuestionData from "./questions/real-numbers/binomial-theorem.json";
import realNumbersProofByInductionQuestionData from "./questions/real-numbers/proof-by-induction.json";
import realNumbersRealNumbersQuestionData from "./questions/real-numbers/real-numbers.json";
import realNumbersSummationNotationQuestionData from "./questions/real-numbers/summation-notation.json";
import trigonometryAngleAdditionFormulaeQuestionData from "./questions/trigonometry/angle-addition-formulae.json";
import trigonometryInverseTrigFunctionsQuestionData from "./questions/trigonometry/inverse-trig-functions.json";
import trigonometryPythagorasTheoremQuestionData from "./questions/trigonometry/pythagoras-theorem.json";
import trigonometryTrigFunctionsQuestionData from "./questions/trigonometry/trig-functions.json";

export const level1MathIPhysicsQuestionTopics = [
  differentiationChainRuleQuestionData,
  differentiationDerivativesQuestionData,
  differentiationFirstPrinciplesQuestionData,
  differentiationHigherOrderDerivativesQuestionData,
  differentiationImplicitDifferentiationQuestionData,
  differentiationInverseDerivativesQuestionData,
  differentiationLhopitalsRuleQuestionData,
  differentiationProductRuleQuestionData,
  differentiationQuotientRuleQuestionData,
  differentiationStandardDerivativesQuestionData,
  functionsFunctionsQuestionData,
  functionsInverseFunctionsQuestionData,
  integrationAntiderivativesQuestionData,
  integrationCoverUpRuleQuestionData,
  integrationDefiniteIntegralsQuestionData,
  integrationFundamentalTheoremQuestionData,
  integrationIntegrationByPartsQuestionData,
  integrationPartialFractionsQuestionData,
  integrationPolynomialDivisionQuestionData,
  integrationRationalIntegralsQuestionData,
  integrationReverseDifferentiationQuestionData,
  integrationStandardIntegralsQuestionData,
  integrationSubstitutionQuestionData,
  integrationTrigPowerIntegralsQuestionData,
  limitsAlgebraicLimitsQuestionData,
  limitsChangeOfVariablesQuestionData,
  limitsContinuityQuestionData,
  limitsFormalLimitsQuestionData,
  limitsLimitLawsQuestionData,
  limitsLimitVariationsQuestionData,
  limitsSineLimitQuestionData,
  limitsSqueezeTheoremQuestionData,
  realNumbersAlgebraicManipulationQuestionData,
  realNumbersBinomialCoefficientsQuestionData,
  realNumbersBinomialTheoremQuestionData,
  realNumbersProofByInductionQuestionData,
  realNumbersRealNumbersQuestionData,
  realNumbersSummationNotationQuestionData,
  trigonometryAngleAdditionFormulaeQuestionData,
  trigonometryInverseTrigFunctionsQuestionData,
  trigonometryPythagorasTheoremQuestionData,
  trigonometryTrigFunctionsQuestionData,
] as const;
