/* This file is generated by apps/academy/scripts/generate-question-registry.mjs. */
/* Do not edit manually. */

import complexArithmeticComplexAdditionQuestionData from "./questions/complex-arithmetic/complex-addition.json";
import complexArithmeticComplexDivisionQuestionData from "./questions/complex-arithmetic/complex-division.json";
import complexArithmeticComplexMultiplicationQuestionData from "./questions/complex-arithmetic/complex-multiplication.json";
import complexArithmeticComplexNumbersQuestionData from "./questions/complex-arithmetic/complex-numbers.json";
import complexArithmeticConjugateQuestionData from "./questions/complex-arithmetic/conjugate.json";
import complexArithmeticImaginaryPartQuestionData from "./questions/complex-arithmetic/imaginary-part.json";
import complexArithmeticModulusQuestionData from "./questions/complex-arithmetic/modulus.json";
import complexArithmeticRealPartQuestionData from "./questions/complex-arithmetic/real-part.json";
import complexEquationsComplexFunctionsQuestionData from "./questions/complex-equations/complex-functions.json";
import complexEquationsFundamentalTheoremQuestionData from "./questions/complex-equations/fundamental-theorem.json";
import complexEquationsGeneralComplexRootsQuestionData from "./questions/complex-equations/general-complex-roots.json";
import complexEquationsLinearComplexEquationsQuestionData from "./questions/complex-equations/linear-complex-equations.json";
import complexEquationsQuadraticComplexEquationsQuestionData from "./questions/complex-equations/quadratic-complex-equations.json";
import complexEquationsRootsOfUnityQuestionData from "./questions/complex-equations/roots-of-unity.json";
import complexEquationsTranscendentalEquationsInAComplexVariableQuestionData from "./questions/complex-equations/transcendental-equations-in-a-complex-variable.json";
import complexFormArgumentQuestionData from "./questions/complex-form/argument.json";
import complexFormComplexAdditionGeometryQuestionData from "./questions/complex-form/complex-addition-geometry.json";
import complexFormComplexExponentialQuestionData from "./questions/complex-form/complex-exponential.json";
import complexFormComplexMultiplicationGeometryQuestionData from "./questions/complex-form/complex-multiplication-geometry.json";
import complexFormComplexTrigFormulaeQuestionData from "./questions/complex-form/complex-trig-formulae.json";
import complexFormDeMoivreTheoremQuestionData from "./questions/complex-form/de-moivre-theorem.json";
import complexFormEulerFormulaQuestionData from "./questions/complex-form/euler-formula.json";
import complexFormPolarFormQuestionData from "./questions/complex-form/polar-form.json";
import differentiationChainRuleQuestionData from "./questions/differentiation/chain-rule.json";
import differentiationDerivativesQuestionData from "./questions/differentiation/derivatives.json";
import differentiationFirstPrinciplesQuestionData from "./questions/differentiation/first-principles.json";
import differentiationHigherOrderDerivativesQuestionData from "./questions/differentiation/higher-order-derivatives.json";
import differentiationImplicitDifferentiationQuestionData from "./questions/differentiation/implicit-differentiation.json";
import differentiationInverseDerivativesQuestionData from "./questions/differentiation/inverse-derivatives.json";
import differentiationLhopitalsRuleQuestionData from "./questions/differentiation/lhopitals-rule.json";
import differentiationProductRuleQuestionData from "./questions/differentiation/product-rule.json";
import differentiationQuotientRuleQuestionData from "./questions/differentiation/quotient-rule.json";
import differentiationStandardDerivativesQuestionData from "./questions/differentiation/standard-derivatives.json";
import functionsFunctionsQuestionData from "./questions/functions/functions.json";
import functionsInverseFunctionsQuestionData from "./questions/functions/inverse-functions.json";
import groupsCyclicGroupsQuestionData from "./questions/groups/cyclic-groups.json";
import groupsGroupAxiomsQuestionData from "./questions/groups/group-axioms.json";
import groupsGroupDefinitionQuestionData from "./questions/groups/group-definition.json";
import groupsGroupMapsQuestionData from "./questions/groups/group-maps.json";
import groupsGroupTablesQuestionData from "./questions/groups/group-tables.json";
import groupsMatrixGroupsQuestionData from "./questions/groups/matrix-groups.json";
import groupsPolygonSymmetriesQuestionData from "./questions/groups/polygon-symmetries.json";
import groupsSubgroupsQuestionData from "./questions/groups/subgroups.json";
import groupsSymmetriesQuestionData from "./questions/groups/symmetries.json";
import integrationAntiderivativesQuestionData from "./questions/integration/antiderivatives.json";
import integrationCoverUpRuleQuestionData from "./questions/integration/cover-up-rule.json";
import integrationDefiniteIntegralsQuestionData from "./questions/integration/definite-integrals.json";
import integrationFundamentalTheoremQuestionData from "./questions/integration/fundamental-theorem.json";
import integrationIntegrationByPartsQuestionData from "./questions/integration/integration-by-parts.json";
import integrationPartialFractionsQuestionData from "./questions/integration/partial-fractions.json";
import integrationPolynomialDivisionQuestionData from "./questions/integration/polynomial-division.json";
import integrationRationalIntegralsQuestionData from "./questions/integration/rational-integrals.json";
import integrationReverseDifferentiationQuestionData from "./questions/integration/reverse-differentiation.json";
import integrationStandardIntegralsQuestionData from "./questions/integration/standard-integrals.json";
import integrationSubstitutionQuestionData from "./questions/integration/substitution.json";
import integrationTrigPowerIntegralsQuestionData from "./questions/integration/trig-power-integrals.json";
import limitsAlgebraicLimitsQuestionData from "./questions/limits/algebraic-limits.json";
import limitsChangeOfVariablesQuestionData from "./questions/limits/change-of-variables.json";
import limitsContinuityQuestionData from "./questions/limits/continuity.json";
import limitsFormalLimitsQuestionData from "./questions/limits/formal-limits.json";
import limitsLimitLawsQuestionData from "./questions/limits/limit-laws.json";
import limitsLimitVariationsQuestionData from "./questions/limits/limit-variations.json";
import limitsSineLimitQuestionData from "./questions/limits/sine-limit.json";
import limitsSqueezeTheoremQuestionData from "./questions/limits/squeeze-theorem.json";
import linearMapsDiagonalisationApplicationsQuestionData from "./questions/linear-maps/diagonalisation-applications.json";
import linearMapsDiagonalisationQuestionData from "./questions/linear-maps/diagonalisation.json";
import linearMapsEigenspacesQuestionData from "./questions/linear-maps/eigenspaces.json";
import linearMapsEigenvaluesQuestionData from "./questions/linear-maps/eigenvalues.json";
import linearMapsEigenvectorsQuestionData from "./questions/linear-maps/eigenvectors.json";
import linearMapsLinearMapsQuestionData from "./questions/linear-maps/linear-maps.json";
import linearMapsMatrixRepresentationsQuestionData from "./questions/linear-maps/matrix-representations.json";
import linearMapsSpecialMatricesQuestionData from "./questions/linear-maps/special-matrices.json";
import matricesDeterminantPropertiesQuestionData from "./questions/matrices/determinant-properties.json";
import matricesDeterminantsQuestionData from "./questions/matrices/determinants.json";
import matricesGaussianEliminationQuestionData from "./questions/matrices/gaussian-elimination.json";
import matricesInverseComputationQuestionData from "./questions/matrices/inverse-computation.json";
import matricesInverseMatricesQuestionData from "./questions/matrices/inverse-matrices.json";
import matricesLinearSystemsQuestionData from "./questions/matrices/linear-systems.json";
import matricesLuDecompositionQuestionData from "./questions/matrices/lu-decomposition.json";
import matricesMatrixNotationQuestionData from "./questions/matrices/matrix-notation.json";
import matricesMatrixOperationsQuestionData from "./questions/matrices/matrix-operations.json";
import matricesRowOperationsQuestionData from "./questions/matrices/row-operations.json";
import matricesRrefQuestionData from "./questions/matrices/rref.json";
import matricesSolutionSetsQuestionData from "./questions/matrices/solution-sets.json";
import powerSeriesCoefficientsQuestionData from "./questions/power-series/coefficients.json";
import powerSeriesIntervalOfConvergenceQuestionData from "./questions/power-series/interval-of-convergence.json";
import powerSeriesPowerSeriesQuestionData from "./questions/power-series/power-series.json";
import powerSeriesRadiusOfConvergenceQuestionData from "./questions/power-series/radius-of-convergence.json";
import powerSeriesRemaindersQuestionData from "./questions/power-series/remainders.json";
import powerSeriesTaylorLimitsQuestionData from "./questions/power-series/taylor-limits.json";
import powerSeriesTaylorPolynomialsQuestionData from "./questions/power-series/taylor-polynomials.json";
import powerSeriesTaylorSeriesQuestionData from "./questions/power-series/taylor-series.json";
import powerSeriesTaylorTheoremQuestionData from "./questions/power-series/taylor-theorem.json";
import realNumbersAlgebraicManipulationQuestionData from "./questions/real-numbers/algebraic-manipulation.json";
import realNumbersBinomialCoefficientsQuestionData from "./questions/real-numbers/binomial-coefficients.json";
import realNumbersBinomialTheoremQuestionData from "./questions/real-numbers/binomial-theorem.json";
import realNumbersProofByInductionQuestionData from "./questions/real-numbers/proof-by-induction.json";
import realNumbersRealNumbersQuestionData from "./questions/real-numbers/real-numbers.json";
import realNumbersSummationNotationQuestionData from "./questions/real-numbers/summation-notation.json";
import seriesAbsoluteConvergenceQuestionData from "./questions/series/absolute-convergence.json";
import seriesConditionalConvergenceQuestionData from "./questions/series/conditional-convergence.json";
import seriesConvergenceTestsQuestionData from "./questions/series/convergence-tests.json";
import seriesGeometricSeriesQuestionData from "./questions/series/geometric-series.json";
import seriesNegativeTermsQuestionData from "./questions/series/negative-terms.json";
import seriesPartialSumsQuestionData from "./questions/series/partial-sums.json";
import seriesPositiveSeriesQuestionData from "./questions/series/positive-series.json";
import seriesSeriesBasicsQuestionData from "./questions/series/series-basics.json";
import seriesSeriesSumsQuestionData from "./questions/series/series-sums.json";
import trigonometryAngleAdditionFormulaeQuestionData from "./questions/trigonometry/angle-addition-formulae.json";
import trigonometryInverseTrigFunctionsQuestionData from "./questions/trigonometry/inverse-trig-functions.json";
import trigonometryPythagorasTheoremQuestionData from "./questions/trigonometry/pythagoras-theorem.json";
import trigonometryTrigFunctionsQuestionData from "./questions/trigonometry/trig-functions.json";
import vectorSpacesBasesQuestionData from "./questions/vector-spaces/bases.json";
import vectorSpacesCoordinatesQuestionData from "./questions/vector-spaces/coordinates.json";
import vectorSpacesDimensionQuestionData from "./questions/vector-spaces/dimension.json";
import vectorSpacesLinearIndependenceQuestionData from "./questions/vector-spaces/linear-independence.json";
import vectorSpacesNullityQuestionData from "./questions/vector-spaces/nullity.json";
import vectorSpacesRankQuestionData from "./questions/vector-spaces/rank.json";
import vectorSpacesSpanningSetsQuestionData from "./questions/vector-spaces/spanning-sets.json";
import vectorSpacesSubspacesQuestionData from "./questions/vector-spaces/subspaces.json";
import vectorSpacesVectorSpacesQuestionData from "./questions/vector-spaces/vector-spaces.json";

export const level1MathIPhysicsQuestionTopics = [
  complexArithmeticComplexAdditionQuestionData,
  complexArithmeticComplexDivisionQuestionData,
  complexArithmeticComplexMultiplicationQuestionData,
  complexArithmeticComplexNumbersQuestionData,
  complexArithmeticConjugateQuestionData,
  complexArithmeticImaginaryPartQuestionData,
  complexArithmeticModulusQuestionData,
  complexArithmeticRealPartQuestionData,
  complexEquationsComplexFunctionsQuestionData,
  complexEquationsFundamentalTheoremQuestionData,
  complexEquationsGeneralComplexRootsQuestionData,
  complexEquationsLinearComplexEquationsQuestionData,
  complexEquationsQuadraticComplexEquationsQuestionData,
  complexEquationsRootsOfUnityQuestionData,
  complexEquationsTranscendentalEquationsInAComplexVariableQuestionData,
  complexFormArgumentQuestionData,
  complexFormComplexAdditionGeometryQuestionData,
  complexFormComplexExponentialQuestionData,
  complexFormComplexMultiplicationGeometryQuestionData,
  complexFormComplexTrigFormulaeQuestionData,
  complexFormDeMoivreTheoremQuestionData,
  complexFormEulerFormulaQuestionData,
  complexFormPolarFormQuestionData,
  differentiationChainRuleQuestionData,
  differentiationDerivativesQuestionData,
  differentiationFirstPrinciplesQuestionData,
  differentiationHigherOrderDerivativesQuestionData,
  differentiationImplicitDifferentiationQuestionData,
  differentiationInverseDerivativesQuestionData,
  differentiationLhopitalsRuleQuestionData,
  differentiationProductRuleQuestionData,
  differentiationQuotientRuleQuestionData,
  differentiationStandardDerivativesQuestionData,
  functionsFunctionsQuestionData,
  functionsInverseFunctionsQuestionData,
  groupsCyclicGroupsQuestionData,
  groupsGroupAxiomsQuestionData,
  groupsGroupDefinitionQuestionData,
  groupsGroupMapsQuestionData,
  groupsGroupTablesQuestionData,
  groupsMatrixGroupsQuestionData,
  groupsPolygonSymmetriesQuestionData,
  groupsSubgroupsQuestionData,
  groupsSymmetriesQuestionData,
  integrationAntiderivativesQuestionData,
  integrationCoverUpRuleQuestionData,
  integrationDefiniteIntegralsQuestionData,
  integrationFundamentalTheoremQuestionData,
  integrationIntegrationByPartsQuestionData,
  integrationPartialFractionsQuestionData,
  integrationPolynomialDivisionQuestionData,
  integrationRationalIntegralsQuestionData,
  integrationReverseDifferentiationQuestionData,
  integrationStandardIntegralsQuestionData,
  integrationSubstitutionQuestionData,
  integrationTrigPowerIntegralsQuestionData,
  limitsAlgebraicLimitsQuestionData,
  limitsChangeOfVariablesQuestionData,
  limitsContinuityQuestionData,
  limitsFormalLimitsQuestionData,
  limitsLimitLawsQuestionData,
  limitsLimitVariationsQuestionData,
  limitsSineLimitQuestionData,
  limitsSqueezeTheoremQuestionData,
  linearMapsDiagonalisationApplicationsQuestionData,
  linearMapsDiagonalisationQuestionData,
  linearMapsEigenspacesQuestionData,
  linearMapsEigenvaluesQuestionData,
  linearMapsEigenvectorsQuestionData,
  linearMapsLinearMapsQuestionData,
  linearMapsMatrixRepresentationsQuestionData,
  linearMapsSpecialMatricesQuestionData,
  matricesDeterminantPropertiesQuestionData,
  matricesDeterminantsQuestionData,
  matricesGaussianEliminationQuestionData,
  matricesInverseComputationQuestionData,
  matricesInverseMatricesQuestionData,
  matricesLinearSystemsQuestionData,
  matricesLuDecompositionQuestionData,
  matricesMatrixNotationQuestionData,
  matricesMatrixOperationsQuestionData,
  matricesRowOperationsQuestionData,
  matricesRrefQuestionData,
  matricesSolutionSetsQuestionData,
  powerSeriesCoefficientsQuestionData,
  powerSeriesIntervalOfConvergenceQuestionData,
  powerSeriesPowerSeriesQuestionData,
  powerSeriesRadiusOfConvergenceQuestionData,
  powerSeriesRemaindersQuestionData,
  powerSeriesTaylorLimitsQuestionData,
  powerSeriesTaylorPolynomialsQuestionData,
  powerSeriesTaylorSeriesQuestionData,
  powerSeriesTaylorTheoremQuestionData,
  realNumbersAlgebraicManipulationQuestionData,
  realNumbersBinomialCoefficientsQuestionData,
  realNumbersBinomialTheoremQuestionData,
  realNumbersProofByInductionQuestionData,
  realNumbersRealNumbersQuestionData,
  realNumbersSummationNotationQuestionData,
  seriesAbsoluteConvergenceQuestionData,
  seriesConditionalConvergenceQuestionData,
  seriesConvergenceTestsQuestionData,
  seriesGeometricSeriesQuestionData,
  seriesNegativeTermsQuestionData,
  seriesPartialSumsQuestionData,
  seriesPositiveSeriesQuestionData,
  seriesSeriesBasicsQuestionData,
  seriesSeriesSumsQuestionData,
  trigonometryAngleAdditionFormulaeQuestionData,
  trigonometryInverseTrigFunctionsQuestionData,
  trigonometryPythagorasTheoremQuestionData,
  trigonometryTrigFunctionsQuestionData,
  vectorSpacesBasesQuestionData,
  vectorSpacesCoordinatesQuestionData,
  vectorSpacesDimensionQuestionData,
  vectorSpacesLinearIndependenceQuestionData,
  vectorSpacesNullityQuestionData,
  vectorSpacesRankQuestionData,
  vectorSpacesSpanningSetsQuestionData,
  vectorSpacesSubspacesQuestionData,
  vectorSpacesVectorSpacesQuestionData,
] as const;
