export const content = String.raw`## Principle

Entropy is a state function. Its change is found by imagining a reversible path between the same initial and final states.

## Notation

<Notation
  items={[
    { symbol: "S", meaning: "entropy", unit: "J K^{-1}" },
    { symbol: "\\Delta S", meaning: "change in entropy", unit: "J K^{-1}" },
    { symbol: "\\delta Q_{\\mathrm{rev}}", meaning: "infinitesimal heat transfer along a reversible path", unit: "J" },
    { symbol: "T", meaning: "absolute temperature", unit: "K" },
    { symbol: "n", meaning: "amount of ideal gas", unit: "mol" },
    { symbol: "R", meaning: "molar gas constant", unit: "J mol^{-1} K^{-1}" },
    { symbol: "L", meaning: "latent heat", unit: "J kg^{-1}" },
    { symbol: "S_{\\mathrm{gen}}", meaning: "entropy generated by irreversibility", unit: "J K^{-1}" },
  ]}
/>

## Method

### Derivation 1: Define entropy change

Heat is path dependent, but entropy is not. To find \\(\\Delta S\\), replace the actual process by any reversible path with the same endpoints and integrate reversible heat over absolute temperature.

<PhysicsDerivation
  items={[
    {
      label: "Differential definition",
      tex: "dS=\\frac{\\delta Q_{\\mathrm{rev}}}{T}",
    },
    {
      label: "Finite change",
      tex: "\\Delta S=\\int_i^f \\frac{\\delta Q_{\\mathrm{rev}}}{T}",
    },
    {
      label: "Constant-temperature reservoir",
      tex: "\\Delta S=\\frac{Q_{\\mathrm{rev}}}{T}",
    },
  ]}
/>

### Derivation 2: Entropy and the second law

For an isolated system, entropy cannot decrease. For a process involving a system and surroundings, add both entropy changes.

<PhysicsDerivation
  items={[
    {
      label: "Universe model",
      tex: "\\Delta S_{\\mathrm{univ}}=\\Delta S_{\\mathrm{sys}}+\\Delta S_{\\mathrm{surr}}",
    },
    {
      label: "Second law",
      tex: "\\Delta S_{\\mathrm{univ}}\\ge 0",
    },
    {
      label: "Reversible limit",
      tex: "\\Delta S_{\\mathrm{univ}}=0",
    },
    {
      label: "Irreversible process",
      tex: "\\Delta S_{\\mathrm{univ}}>0",
    },
  ]}
/>

### Derivation 3: Ideal-gas entropy change

For an ideal gas, use a reversible path made from a constant-volume temperature change and an isothermal volume change.

<PhysicsDerivation
  items={[
    {
      label: "Constant volume",
      tex: "\\Delta S_V=nC_V\\ln\\!\\left(\\frac{T_f}{T_i}\\right)",
    },
    {
      label: "Isothermal volume change",
      tex: "\\Delta S_T=nR\\ln\\!\\left(\\frac{V_f}{V_i}\\right)",
    },
    {
      label: "Combined ideal-gas result",
      tex: "\\Delta S=nC_V\\ln\\!\\left(\\frac{T_f}{T_i}\\right)+nR\\ln\\!\\left(\\frac{V_f}{V_i}\\right)",
    },
  ]}
/>

## Rules

Use these as entropy building blocks.

<Equation label="Entropy definition" tex="\Delta S=\int_i^f \frac{\delta Q_{\mathrm{rev}}}{T}" />

<Equation label="Constant-temperature process" tex="\Delta S=\frac{Q_{\mathrm{rev}}}{T}" />

<Equation label="Phase change at temperature T" tex="\Delta S=\frac{mL}{T}" />

<Equation label="Ideal gas: T and V form" tex="\Delta S=nC_V\ln\!\left(\frac{T_f}{T_i}\right)+nR\ln\!\left(\frac{V_f}{V_i}\right)" />

<Equation label="Ideal gas: T and p form" tex="\Delta S=nC_P\ln\!\left(\frac{T_f}{T_i}\right)-nR\ln\!\left(\frac{p_f}{p_i}\right)" />

<Equation label="Second-law test" tex="\Delta S_{\mathrm{univ}}=\Delta S_{\mathrm{sys}}+\Delta S_{\mathrm{surr}}\ge 0" />

## Examples

<PhysicsExamples
  items={[
    {
      title: "Example 1",
      question: "A reservoir at \\(300\\,\\mathrm{K}\\) receives \\(900\\,\\mathrm{J}\\) of heat reversibly. Find its entropy change.",
      answer: "For a constant-temperature reservoir, \\(\\Delta S=Q/T\\). Thus \\(\\Delta S=900/300=3.0\\,\\mathrm{J\\,K^{-1}}\\).",
    },
    {
      title: "Example 2",
      question: "One mole of ideal gas expands isothermally to twice its initial volume. Find \\(\\Delta S\\).",
      answer: "For isothermal ideal-gas expansion, \\(\\Delta S=nR\\ln(V_f/V_i)=R\\ln2=5.76\\,\\mathrm{J\\,K^{-1}}\\).",
    },
    {
      title: "Example 3",
      question: "\\(600\\,\\mathrm{J}\\) of heat flows from a \\(400\\,\\mathrm{K}\\) reservoir to a \\(300\\,\\mathrm{K}\\) reservoir. Find \\(\\Delta S_{\\mathrm{univ}}\\).",
      answer: "The hot reservoir changes by \\(-600/400=-1.5\\,\\mathrm{J\\,K^{-1}}\\). The cold reservoir changes by \\(600/300=2.0\\,\\mathrm{J\\,K^{-1}}\\). The universe changes by \\(0.5\\,\\mathrm{J\\,K^{-1}}\\), so the process is irreversible.",
    },
  ]}
/>

## Checks

- Entropy change is found from a reversible path even if the real process is irreversible.
- The temperature in entropy formulas must be in kelvin.
- The shortcut \\(\\Delta S=Q/T\\) requires a reversible heat transfer at constant temperature.
- A system's entropy can decrease, but the entropy change of system plus surroundings cannot be negative.
- Free expansion of an ideal gas has \\(Q=0\\) and \\(W=0\\), but its entropy still increases because the endpoint volume is larger.`;
