/* This file is generated by apps/academy/scripts/generate-question-registry.mjs. */
/* Do not edit manually. */

import complexAnalysisCauchyRiemannEquationsQuestionData from "./questions/complex-analysis/cauchy-riemann-equations.json";
import complexAnalysisComplexDerivativeExamplesQuestionData from "./questions/complex-analysis/complex-derivative-examples.json";
import complexAnalysisComplexDifferentiabilityQuestionData from "./questions/complex-analysis/complex-differentiability.json";
import complexAnalysisHarmonicFunctionsQuestionData from "./questions/complex-analysis/harmonic-functions.json";
import complexAnalysisLaplaceEquationQuestionData from "./questions/complex-analysis/laplace-equation.json";
import fourierAnalysisComplexFourierFormQuestionData from "./questions/fourier-analysis/complex-fourier-form.json";
import fourierAnalysisEulerFormulaeQuestionData from "./questions/fourier-analysis/euler-formulae.json";
import fourierAnalysisEvenFunctionsQuestionData from "./questions/fourier-analysis/even-functions.json";
import fourierAnalysisFourierCoefficientsQuestionData from "./questions/fourier-analysis/fourier-coefficients.json";
import fourierAnalysisFourierSeriesQuestionData from "./questions/fourier-analysis/fourier-series.json";
import fourierAnalysisFourierSymmetryQuestionData from "./questions/fourier-analysis/fourier-symmetry.json";
import fourierAnalysisFunctionInnerProductQuestionData from "./questions/fourier-analysis/function-inner-product.json";
import fourierAnalysisFunctionNormQuestionData from "./questions/fourier-analysis/function-norm.json";
import fourierAnalysisGeneralPeriodsQuestionData from "./questions/fourier-analysis/general-periods.json";
import fourierAnalysisOddFunctionsQuestionData from "./questions/fourier-analysis/odd-functions.json";
import fourierAnalysisOrthogonalFunctionsQuestionData from "./questions/fourier-analysis/orthogonal-functions.json";
import fourierAnalysisParsevalTheoremQuestionData from "./questions/fourier-analysis/parseval-theorem.json";
import fourierAnalysisPeriodicFunctionsQuestionData from "./questions/fourier-analysis/periodic-functions.json";
import fourierAnalysisVectorAnalogyQuestionData from "./questions/fourier-analysis/vector-analogy.json";
import kinematicsAccelerationQuestionData from "./questions/kinematics/acceleration.json";
import kinematicsAngularMomentumQuestionData from "./questions/kinematics/angular-momentum.json";
import kinematicsCylindricalPolarsQuestionData from "./questions/kinematics/cylindrical-polars.json";
import kinematicsEnergyQuestionData from "./questions/kinematics/energy.json";
import kinematicsForcesQuestionData from "./questions/kinematics/forces.json";
import kinematicsPolarCoordinatesQuestionData from "./questions/kinematics/polar-coordinates.json";
import kinematicsPositionQuestionData from "./questions/kinematics/position.json";
import kinematicsVelocityQuestionData from "./questions/kinematics/velocity.json";
import kinematicsWorkDoneQuestionData from "./questions/kinematics/work-done.json";
import multipleIntegralsCylindricalCoordinatesQuestionData from "./questions/multiple-integrals/cylindrical-coordinates.json";
import multipleIntegralsDoubleIntegralsQuestionData from "./questions/multiple-integrals/double-integrals.json";
import multipleIntegralsIntegrationLimitsQuestionData from "./questions/multiple-integrals/integration-limits.json";
import multipleIntegralsJacobianQuestionData from "./questions/multiple-integrals/jacobian.json";
import multipleIntegralsOrderSwitchingQuestionData from "./questions/multiple-integrals/order-switching.json";
import multipleIntegralsPolarIntegrationQuestionData from "./questions/multiple-integrals/polar-integration.json";
import multipleIntegralsRectangularRegionsQuestionData from "./questions/multiple-integrals/rectangular-regions.json";
import multipleIntegralsSphericalCoordinatesQuestionData from "./questions/multiple-integrals/spherical-coordinates.json";
import multipleIntegralsTripleIntegralsQuestionData from "./questions/multiple-integrals/triple-integrals.json";
import multipleIntegralsVolumeInterpretationQuestionData from "./questions/multiple-integrals/volume-interpretation.json";
import multivariableCalculusClairautTheoremQuestionData from "./questions/multivariable-calculus/clairaut-theorem.json";
import multivariableCalculusCriticalPointsQuestionData from "./questions/multivariable-calculus/critical-points.json";
import multivariableCalculusDifferentialsQuestionData from "./questions/multivariable-calculus/differentials.json";
import multivariableCalculusDirectionalDerivativesQuestionData from "./questions/multivariable-calculus/directional-derivatives.json";
import multivariableCalculusExactDifferentialsQuestionData from "./questions/multivariable-calculus/exact-differentials.json";
import multivariableCalculusGradientQuestionData from "./questions/multivariable-calculus/gradient.json";
import multivariableCalculusGraphsQuestionData from "./questions/multivariable-calculus/graphs.json";
import multivariableCalculusHigherPartialDerivativesQuestionData from "./questions/multivariable-calculus/higher-partial-derivatives.json";
import multivariableCalculusInexactDifferentialsQuestionData from "./questions/multivariable-calculus/inexact-differentials.json";
import multivariableCalculusMultiParameterChainRuleQuestionData from "./questions/multivariable-calculus/multi-parameter-chain-rule.json";
import multivariableCalculusMultivariableChainRuleQuestionData from "./questions/multivariable-calculus/multivariable-chain-rule.json";
import multivariableCalculusMultivariableFunctionsQuestionData from "./questions/multivariable-calculus/multivariable-functions.json";
import multivariableCalculusNDimensionalCriticalPointsQuestionData from "./questions/multivariable-calculus/n-dimensional-critical-points.json";
import multivariableCalculusPartialDerivativesQuestionData from "./questions/multivariable-calculus/partial-derivatives.json";
import multivariableCalculusSingleParameterChainRuleQuestionData from "./questions/multivariable-calculus/single-parameter-chain-rule.json";
import multivariableCalculusTaylorExpansionsQuestionData from "./questions/multivariable-calculus/taylor-expansions.json";
import multivariableCalculusTwoDimensionalCriticalPointsQuestionData from "./questions/multivariable-calculus/two-dimensional-critical-points.json";
import ordinaryDifferentialEquationsBernoulliEquationsQuestionData from "./questions/ordinary-differential-equations/bernoulli-equations.json";
import ordinaryDifferentialEquationsBoundaryConditionsQuestionData from "./questions/ordinary-differential-equations/boundary-conditions.json";
import ordinaryDifferentialEquationsCarSuspensionQuestionData from "./questions/ordinary-differential-equations/car-suspension.json";
import ordinaryDifferentialEquationsDependentVariablesQuestionData from "./questions/ordinary-differential-equations/dependent-variables.json";
import ordinaryDifferentialEquationsEquationOrderQuestionData from "./questions/ordinary-differential-equations/equation-order.json";
import ordinaryDifferentialEquationsHomogeneousConstantCoefficientEquationsQuestionData from "./questions/ordinary-differential-equations/homogeneous-constant-coefficient-equations.json";
import ordinaryDifferentialEquationsHomogeneousEquationsQuestionData from "./questions/ordinary-differential-equations/homogeneous-equations.json";
import ordinaryDifferentialEquationsIndependentVariablesQuestionData from "./questions/ordinary-differential-equations/independent-variables.json";
import ordinaryDifferentialEquationsInhomogeneousConstantCoefficientEquationsQuestionData from "./questions/ordinary-differential-equations/inhomogeneous-constant-coefficient-equations.json";
import ordinaryDifferentialEquationsInitialConditionsQuestionData from "./questions/ordinary-differential-equations/initial-conditions.json";
import ordinaryDifferentialEquationsLinearFirstOrderEquationsQuestionData from "./questions/ordinary-differential-equations/linear-first-order-equations.json";
import ordinaryDifferentialEquationsLinearSecondOrderEquationsQuestionData from "./questions/ordinary-differential-equations/linear-second-order-equations.json";
import ordinaryDifferentialEquationsOdeIntroductionQuestionData from "./questions/ordinary-differential-equations/ode-introduction.json";
import ordinaryDifferentialEquationsOperatorMethodsQuestionData from "./questions/ordinary-differential-equations/operator-methods.json";
import ordinaryDifferentialEquationsResonanceQuestionData from "./questions/ordinary-differential-equations/resonance.json";
import ordinaryDifferentialEquationsSecondOrderEquationsQuestionData from "./questions/ordinary-differential-equations/second-order-equations.json";
import ordinaryDifferentialEquationsSeparableEquationsQuestionData from "./questions/ordinary-differential-equations/separable-equations.json";
import ordinaryDifferentialEquationsSimultaneousFirstOrderEquationsQuestionData from "./questions/ordinary-differential-equations/simultaneous-first-order-equations.json";
import partialDifferentialEquationsImportantPdesQuestionData from "./questions/partial-differential-equations/important-pdes.json";
import partialDifferentialEquationsLinearPdesQuestionData from "./questions/partial-differential-equations/linear-pdes.json";
import partialDifferentialEquationsPdeIntroductionQuestionData from "./questions/partial-differential-equations/pde-introduction.json";
import partialDifferentialEquationsSeparationOfVariablesQuestionData from "./questions/partial-differential-equations/separation-of-variables.json";
import partialDifferentialEquationsSpecialCasesQuestionData from "./questions/partial-differential-equations/special-cases.json";
import probabilityBayesTheoremQuestionData from "./questions/probability/bayes-theorem.json";
import probabilityBinomialDistributionQuestionData from "./questions/probability/binomial-distribution.json";
import probabilityCentralLimitTheoremQuestionData from "./questions/probability/central-limit-theorem.json";
import probabilityConditionalProbabilityQuestionData from "./questions/probability/conditional-probability.json";
import probabilityContinuousRandomVariablesQuestionData from "./questions/probability/continuous-random-variables.json";
import probabilityCountingPrinciplesQuestionData from "./questions/probability/counting-principles.json";
import probabilityDiscreteRandomVariablesQuestionData from "./questions/probability/discrete-random-variables.json";
import probabilityEventsQuestionData from "./questions/probability/events.json";
import probabilityExpectationQuestionData from "./questions/probability/expectation.json";
import probabilityExperimentalErrorsQuestionData from "./questions/probability/experimental-errors.json";
import probabilityGeneralNormalQuestionData from "./questions/probability/general-normal.json";
import probabilityIndependenceQuestionData from "./questions/probability/independence.json";
import probabilityNormalApproximationQuestionData from "./questions/probability/normal-approximation.json";
import probabilityNormalDistributionQuestionData from "./questions/probability/normal-distribution.json";
import probabilityPartitionsQuestionData from "./questions/probability/partitions.json";
import probabilityPoissonApproximationQuestionData from "./questions/probability/poisson-approximation.json";
import probabilityPoissonDistributionQuestionData from "./questions/probability/poisson-distribution.json";
import probabilityProbabilityAxiomsQuestionData from "./questions/probability/probability-axioms.json";
import probabilityProbabilityQuestionData from "./questions/probability/probability.json";
import probabilitySampleMeanQuestionData from "./questions/probability/sample-mean.json";
import probabilityStandardNormalQuestionData from "./questions/probability/standard-normal.json";
import probabilityVarianceQuestionData from "./questions/probability/variance.json";
import vectorCalculusCurlQuestionData from "./questions/vector-calculus/curl.json";
import vectorCalculusDivGradCurlIdentitiesQuestionData from "./questions/vector-calculus/div-grad-curl-identities.json";
import vectorCalculusDivergenceQuestionData from "./questions/vector-calculus/divergence.json";
import vectorCalculusGradientOperatorQuestionData from "./questions/vector-calculus/gradient-operator.json";
import vectorCalculusMaxwellEquationsQuestionData from "./questions/vector-calculus/maxwell-equations.json";
import vectorCalculusVectorFieldsQuestionData from "./questions/vector-calculus/vector-fields.json";
import vectorsCoordinateBasesQuestionData from "./questions/vectors/coordinate-bases.json";
import vectorsCrossProductQuestionData from "./questions/vectors/cross-product.json";
import vectorsDotProductQuestionData from "./questions/vectors/dot-product.json";
import vectorsLinesQuestionData from "./questions/vectors/lines.json";
import vectorsPlanesQuestionData from "./questions/vectors/planes.json";
import vectorsScalarMultiplicationQuestionData from "./questions/vectors/scalar-multiplication.json";
import vectorsScalarTripleProductQuestionData from "./questions/vectors/scalar-triple-product.json";
import vectorsScalarsQuestionData from "./questions/vectors/scalars.json";
import vectorsVectorAdditionQuestionData from "./questions/vectors/vector-addition.json";
import vectorsVectorSpacesQuestionData from "./questions/vectors/vector-spaces.json";
import vectorsVectorsQuestionData from "./questions/vectors/vectors.json";
import vectorsZeroVectorQuestionData from "./questions/vectors/zero-vector.json";

export const level1MathIIPhysicsQuestionTopics = [
  complexAnalysisCauchyRiemannEquationsQuestionData,
  complexAnalysisComplexDerivativeExamplesQuestionData,
  complexAnalysisComplexDifferentiabilityQuestionData,
  complexAnalysisHarmonicFunctionsQuestionData,
  complexAnalysisLaplaceEquationQuestionData,
  fourierAnalysisComplexFourierFormQuestionData,
  fourierAnalysisEulerFormulaeQuestionData,
  fourierAnalysisEvenFunctionsQuestionData,
  fourierAnalysisFourierCoefficientsQuestionData,
  fourierAnalysisFourierSeriesQuestionData,
  fourierAnalysisFourierSymmetryQuestionData,
  fourierAnalysisFunctionInnerProductQuestionData,
  fourierAnalysisFunctionNormQuestionData,
  fourierAnalysisGeneralPeriodsQuestionData,
  fourierAnalysisOddFunctionsQuestionData,
  fourierAnalysisOrthogonalFunctionsQuestionData,
  fourierAnalysisParsevalTheoremQuestionData,
  fourierAnalysisPeriodicFunctionsQuestionData,
  fourierAnalysisVectorAnalogyQuestionData,
  kinematicsAccelerationQuestionData,
  kinematicsAngularMomentumQuestionData,
  kinematicsCylindricalPolarsQuestionData,
  kinematicsEnergyQuestionData,
  kinematicsForcesQuestionData,
  kinematicsPolarCoordinatesQuestionData,
  kinematicsPositionQuestionData,
  kinematicsVelocityQuestionData,
  kinematicsWorkDoneQuestionData,
  multipleIntegralsCylindricalCoordinatesQuestionData,
  multipleIntegralsDoubleIntegralsQuestionData,
  multipleIntegralsIntegrationLimitsQuestionData,
  multipleIntegralsJacobianQuestionData,
  multipleIntegralsOrderSwitchingQuestionData,
  multipleIntegralsPolarIntegrationQuestionData,
  multipleIntegralsRectangularRegionsQuestionData,
  multipleIntegralsSphericalCoordinatesQuestionData,
  multipleIntegralsTripleIntegralsQuestionData,
  multipleIntegralsVolumeInterpretationQuestionData,
  multivariableCalculusClairautTheoremQuestionData,
  multivariableCalculusCriticalPointsQuestionData,
  multivariableCalculusDifferentialsQuestionData,
  multivariableCalculusDirectionalDerivativesQuestionData,
  multivariableCalculusExactDifferentialsQuestionData,
  multivariableCalculusGradientQuestionData,
  multivariableCalculusGraphsQuestionData,
  multivariableCalculusHigherPartialDerivativesQuestionData,
  multivariableCalculusInexactDifferentialsQuestionData,
  multivariableCalculusMultiParameterChainRuleQuestionData,
  multivariableCalculusMultivariableChainRuleQuestionData,
  multivariableCalculusMultivariableFunctionsQuestionData,
  multivariableCalculusNDimensionalCriticalPointsQuestionData,
  multivariableCalculusPartialDerivativesQuestionData,
  multivariableCalculusSingleParameterChainRuleQuestionData,
  multivariableCalculusTaylorExpansionsQuestionData,
  multivariableCalculusTwoDimensionalCriticalPointsQuestionData,
  ordinaryDifferentialEquationsBernoulliEquationsQuestionData,
  ordinaryDifferentialEquationsBoundaryConditionsQuestionData,
  ordinaryDifferentialEquationsCarSuspensionQuestionData,
  ordinaryDifferentialEquationsDependentVariablesQuestionData,
  ordinaryDifferentialEquationsEquationOrderQuestionData,
  ordinaryDifferentialEquationsHomogeneousConstantCoefficientEquationsQuestionData,
  ordinaryDifferentialEquationsHomogeneousEquationsQuestionData,
  ordinaryDifferentialEquationsIndependentVariablesQuestionData,
  ordinaryDifferentialEquationsInhomogeneousConstantCoefficientEquationsQuestionData,
  ordinaryDifferentialEquationsInitialConditionsQuestionData,
  ordinaryDifferentialEquationsLinearFirstOrderEquationsQuestionData,
  ordinaryDifferentialEquationsLinearSecondOrderEquationsQuestionData,
  ordinaryDifferentialEquationsOdeIntroductionQuestionData,
  ordinaryDifferentialEquationsOperatorMethodsQuestionData,
  ordinaryDifferentialEquationsResonanceQuestionData,
  ordinaryDifferentialEquationsSecondOrderEquationsQuestionData,
  ordinaryDifferentialEquationsSeparableEquationsQuestionData,
  ordinaryDifferentialEquationsSimultaneousFirstOrderEquationsQuestionData,
  partialDifferentialEquationsImportantPdesQuestionData,
  partialDifferentialEquationsLinearPdesQuestionData,
  partialDifferentialEquationsPdeIntroductionQuestionData,
  partialDifferentialEquationsSeparationOfVariablesQuestionData,
  partialDifferentialEquationsSpecialCasesQuestionData,
  probabilityBayesTheoremQuestionData,
  probabilityBinomialDistributionQuestionData,
  probabilityCentralLimitTheoremQuestionData,
  probabilityConditionalProbabilityQuestionData,
  probabilityContinuousRandomVariablesQuestionData,
  probabilityCountingPrinciplesQuestionData,
  probabilityDiscreteRandomVariablesQuestionData,
  probabilityEventsQuestionData,
  probabilityExpectationQuestionData,
  probabilityExperimentalErrorsQuestionData,
  probabilityGeneralNormalQuestionData,
  probabilityIndependenceQuestionData,
  probabilityNormalApproximationQuestionData,
  probabilityNormalDistributionQuestionData,
  probabilityPartitionsQuestionData,
  probabilityPoissonApproximationQuestionData,
  probabilityPoissonDistributionQuestionData,
  probabilityProbabilityAxiomsQuestionData,
  probabilityProbabilityQuestionData,
  probabilitySampleMeanQuestionData,
  probabilityStandardNormalQuestionData,
  probabilityVarianceQuestionData,
  vectorCalculusCurlQuestionData,
  vectorCalculusDivGradCurlIdentitiesQuestionData,
  vectorCalculusDivergenceQuestionData,
  vectorCalculusGradientOperatorQuestionData,
  vectorCalculusMaxwellEquationsQuestionData,
  vectorCalculusVectorFieldsQuestionData,
  vectorsCoordinateBasesQuestionData,
  vectorsCrossProductQuestionData,
  vectorsDotProductQuestionData,
  vectorsLinesQuestionData,
  vectorsPlanesQuestionData,
  vectorsScalarMultiplicationQuestionData,
  vectorsScalarTripleProductQuestionData,
  vectorsScalarsQuestionData,
  vectorsVectorAdditionQuestionData,
  vectorsVectorSpacesQuestionData,
  vectorsVectorsQuestionData,
  vectorsZeroVectorQuestionData,
] as const;
